// words_hsk4_adv.js – HSK 4 advanced (words 601–1200) with examples
window.HSK4_WORDS = [
  {word:"爱情", pinyin:"ài qíng", meaning:"love (between a man and a woman)", example:"这是一个感人的爱情故事。"},
  {word:"安排", pinyin:"ānpái", meaning:"plan in detail; arrange", example:"下午的会议，我已经安排好了。"},
  {word:"安全", pinyin:"ānquán", meaning:"safe; safety", example:"晚上开车要注意安全。"},
  {word:"按时", pinyin:"ànshí", meaning:"on time; on schedule; punctually", example:"我按时完成了任务。"},
  {word:"按照", pinyin:"ànzhào", meaning:"according to", example:"请按照要求把报告改一下。"},
  {word:"百分之", pinyin:"bǎifēnzhī", meaning:"percent", example:"任务完成百分之八十了。"},
  {word:"棒", pinyin:"bàng", meaning:"great; good; excellent", example:"你的字写得真棒！"},
  {word:"包子", pinyin:"bāozi", meaning:"steamed stuffed bun", example:"这家饭馆儿的包子味道非常好。"},
  {word:"保护", pinyin:"bǎohù", meaning:"protect", example:"人们应该保护环境。"},
  {word:"保证", pinyin:"bǎozhèng", meaning:"guarantee; ensure; promise", example:"我保证，以后不迟到了。"},
  {word:"报名", pinyin:"bàomíng", meaning:"enroll; sign up", example:"你想报名参加运动会吗？"},
  {word:"抱", pinyin:"bào", meaning:"hold sb or sth with one's arm(s); embrace", example:"他把孩子抱了起来。"},
  {word:"抱歉", pinyin:"bàoqiàn", meaning:"be sorry; feel apologetic; regret", example:"非常抱歉，让您等了这么久。"},
  {word:"倍", pinyin:"bèi", meaning:"times (of the original number or quantity)", example:"我们学校的留学生比去年多了一倍。"},
  {word:"本来", pinyin:"běnlái", meaning:"originally", example:"我本来要去看演出，但是突然有事儿不能去了。"},
  {word:"笨", pinyin:"bèn", meaning:"dull; foolish; stupid", example:"你并不笨，只是需要更努力。"},
  {word:"比如", pinyin:"bǐrú", meaning:"take sth for example", example:"我有很多爱好，比如游泳和读书。"},
  {word:"毕业", pinyin:"bìyè", meaning:"graduate", example:"我今年上大三，明年毕业。"},
  {word:"遍", pinyin:"biàn", meaning:"number of times", example:"这篇文章，我读了很多遍。"},
  {word:"标准", pinyin:"biāozhǔn", meaning:"standard; conforming to a standard", example:"你选男友的标准太高了。"},
  {word:"表格", pinyin:"biǎogé", meaning:"form; table; list", example:"请在表格里填上您的姓名。"},
  {word:"表示", pinyin:"biǎoshì", meaning:"express; convey", example:"他表示愿意继续在公司工作。"},
  {word:"表演", pinyin:"biǎoyǎn", meaning:"act; perform; show", example:"你们要表演什么节目？"},
  {word:"表扬", pinyin:"biǎoyáng", meaning:"praise", example:"小明喜欢帮助别人，老师表扬了他。"},
  {word:"饼干", pinyin:"bǐnggān", meaning:"cracker; cookie; biscuit", example:"我买了饼干，吃点儿吧。"},
  {word:"并且", pinyin:"bìngqiě", meaning:"further more; besides", example:"她很聪明，并且很努力。"},
  {word:"博士", pinyin:"bóshì", meaning:"doctor (an academic degree)", example:"我来介绍一下，这位是李博士。"},
  {word:"不过", pinyin:"búguò", meaning:"but; however", example:"他很优秀，不过不符合公司的招聘条件。"},
  {word:"不得不", pinyin:"bùdébù", meaning:"must; have to", example:"任务还没完成，所以周末我们不得不加班。"},
  {word:"不管", pinyin:"bùguǎn", meaning:"no matter; whether or not", example:"不管天怎么样，我都要爬山。"},
  {word:"不好意思", pinyin:"bùhǎoyìsi", meaning:"feel shy or sorry", example:"大家都看着他，他有点儿不好意思了。"},
  {word:"不仅", pinyin:"bùjǐn", meaning:"not only", example:"我不仅去过那个城市，而且去过很多次。"},
  {word:"部分", pinyin:"bùfen", meaning:"part; section; portion", example:"这本小说由四部分组成。"},
  {word:"擦", pinyin:"cā", meaning:"rub or wipe in order to clean", example:"我已经把窗户擦干净了。"},
  {word:"猜", pinyin:"cāi", meaning:"guess", example:"你猜我给你准备了什么生日礼物？"},
  {word:"材料", pinyin:"cáiliào", meaning:"reference material", example:"报名需要什么材料？"},
  {word:"参观", pinyin:"cānguān", meaning:"visit for learning", example:"学校组织大家去长城参观。"},
  {word:"餐厅", pinyin:"cāntīng", meaning:"restaurant", example:"学校附近新开了一家餐厅。"},
  {word:"厕所", pinyin:"cèsuǒ", meaning:"toilet; bathroom; washroom", example:"男厕所在二层。"},
  {word:"差不多", pinyin:"chàbuduō", meaning:"about; nearly", example:"我每天差不多7点起床。"},
  {word:"长城", pinyin:"Chángchéng", meaning:"the Great Wall", example:"我想周末去参观长城。"},
  {word:"长江", pinyin:"Chángjiāng", meaning:"the Yangtze River", example:"长江是中国的第一大河。"},
  {word:"尝", pinyin:"cháng", meaning:"taste", example:"快来尝尝我做的菜，味道怎么样？"},
  {word:"场", pinyin:"chǎng", meaning:"used for activities", example:"今年下午有场足球比赛。"},
  {word:"超过", pinyin:"chāoguò", meaning:"leave behind; outstrip", example:"每天有超过三百个航班在这里起飞。"},
  {word:"吵", pinyin:"chǎo", meaning:"noisy; quarrel", example:"外面太吵了，我睡不着。"},
  {word:"成功", pinyin:"chénggōng", meaning:"succeed; success", example:"太好了，我们终于成功了。"},
  {word:"成为", pinyin:"chéngwéi", meaning:"become", example:"几年不见，她现在已经成了一名医生。"},
  {word:"诚实", pinyin:"chéngshí", meaning:"honest", example:"诚实的人值得我们尊重。"},
  {word:"乘坐", pinyin:"chéngzuò", meaning:"take a ride (in a car, ship, etc.)", example:"欢迎您乘坐本次航班。"},
  {word:"吃惊", pinyin:"chījīng", meaning:"be startled; be shocked", example:"这个消息非常令人吃惊。"},
  {word:"重新", pinyin:"chóngxīn", meaning:"once again", example:"他把事情重新说了一遍。"},
  {word:"抽烟", pinyin:"chōuyān", meaning:"smoke a cigarette", example:"对不起，医院里不能抽烟。"},
  {word:"出差", pinyin:"chūchāi", meaning:"be on a business trip", example:"爸爸已经出差一个多月了。"},
  {word:"出发", pinyin:"chūfā", meaning:"set out; start off; leave", example:"我从北京出发去上海。"},
  {word:"出生", pinyin:"chūshēng", meaning:"be born", example:"女儿是1990年出生的。"},
  {word:"厨房", pinyin:"chúfáng", meaning:"kitchen", example:"我正在厨房里做饭呢。"},
  {word:"传真", pinyin:"chuánzhēn", meaning:"fax", example:"请帮我发一份传真。"},
  {word:"窗户", pinyin:"chuānghu", meaning:"window", example:"她坐在窗户旁边安静地看书。"},
  {word:"词语", pinyin:"cíyǔ", meaning:"word and phrase", example:"请把你们不认识的词语都找出来。"},
  {word:"从来", pinyin:"cónglái", meaning:"right from the beginning; always", example:"我从来没见过他。"},
  {word:"粗心", pinyin:"cūxīn", meaning:"careless; thoughtless", example:"你真是太粗心了。"},
  {word:"存", pinyin:"cún", meaning:"keep; save; deposit", example:"我把钱存进了银行。"},
  {word:"错误", pinyin:"cuòwù", meaning:"wrong; error", example:"我觉得这种说法是错误的。"},
  {word:"答案", pinyin:"dá’àn", meaning:"answer", example:"我不知道这道题的答案。"},
  {word:"打扮", pinyin:"dǎban", meaning:"dress up; make up", example:"她简单打扮了一下就出门了。"},
  {word:"打扰", pinyin:"dǎrǎo", meaning:"bother; interrupt", example:"对不起，打扰一下，王教授在吗？"},
  {word:"打印", pinyin:"dǎyìn", meaning:"print", example:"这些材料已经打印完了。"},
  {word:"打招呼", pinyin:"dǎzhāohu", meaning:"greet sb by word or gesture", example:"他笑着和我打招呼。"},
  {word:"打折", pinyin:"dǎzhé", meaning:"give a discount", example:"春节前，商场都在打折。"},
  {word:"打针", pinyin:"dǎzhēn", meaning:"give or have an injection", example:"儿子非常害怕打针。"},
  {word:"大概", pinyin:"dàgài", meaning:"almost; probably", example:"他大概不会来了。"},
  {word:"大使馆", pinyin:"dàshǐguǎn", meaning:"embassy", example:"我明天要去大使馆办签证。"},
  {word:"大约", pinyin:"dàyuē", meaning:"about; approximately", example:"他大约有三十多岁。"},
  {word:"大夫", pinyin:"dàifu", meaning:"doctor; physician", example:"李大夫，您明天上午在医院吗？"},
  {word:"戴", pinyin:"dài", meaning:"wear; put on", example:"外边风大，戴上帽子吧。"},
  {word:"当时", pinyin:"dāngshí", meaning:"at that time", example:"我记不清楚当时的情况了。"},
  {word:"刀", pinyin:"dāo", meaning:"knife", example:"水果刀在厨房里。"},
  {word:"导游", pinyin:"dǎoyóu", meaning:"tour guide", example:"我的姐姐是一名导游。"},
  {word:"倒", pinyin:"dǎo", meaning:"fall; lie down", example:"大风把树刮倒了。"},
  {word:"到处", pinyin:"dàochù", meaning:"everywhere", example:"公园里到处是鲜花。"},
  {word:"到底", pinyin:"dàodǐ", meaning:"on earth", example:"这句话到底是什么意思？"},
  {word:"道歉", pinyin:"dàoqiàn", meaning:"make an apology", example:"我已经向他道歉了。"},
  {word:"得意", pinyin:"déyì", meaning:"be pleased with oneself", example:"工作取得了成功，大家都很得意。"},
  {word:"得", pinyin:"de", meaning:"marker of complement; get", example:"你走得太快了。"},
  {word:"登机牌", pinyin:"dēngjīpái", meaning:"boarding pass", example:"请您拿好登机牌，准备登机。"},
  {word:"等", pinyin:"děng", meaning:"and so on; etc.", example:"这个学期我选了很多课，有艺术、历史、经济等。"},
  {word:"低", pinyin:"dī", meaning:"low; lower", example:"这颗树比房子低。"},
  {word:"底", pinyin:"dǐ", meaning:"at the end of", example:"年底公司会给大家发奖金。"},
  {word:"地点", pinyin:"dìdiǎn", meaning:"place; site", example:"开会的地点在二楼会议室。"},
  {word:"地球", pinyin:"dìqiú", meaning:"the Earth", example:"地球上70%的面积是海洋。"},
  {word:"地址", pinyin:"dìzhǐ", meaning:"address", example:"请把您的地址写下来。"},
  {word:"调查", pinyin:"diàochá", meaning:"investigate; investigation", example:"警察正在进行调查。"},
  {word:"掉", pinyin:"diào", meaning:"fall", example:"我把钥匙掉在了地上。"},
  {word:"丢", pinyin:"diū", meaning:"lose", example:"你的书包丢了？"},
  {word:"动作", pinyin:"dòngzuò", meaning:"movement; action", example:"我教你跳舞吧，动作很简单。"},
  {word:"堵车", pinyin:"dǔchē", meaning:"traffic jam", example:"我在路上，又堵车了。"},
  {word:"肚子", pinyin:"dùzi", meaning:"belly; stomach", example:"我肚子疼。"},
  {word:"短信", pinyin:"duǎnxìn", meaning:"short message", example:"有事儿请给我发短信或者打电话。"},
  {word:"对话", pinyin:"duìhuà", meaning:"dialogue", example:"这个对话比较简单，我能听懂。"},
  {word:"对面", pinyin:"duìmiàn", meaning:"the opposite side", example:"我就住在学校对面。"},
  {word:"儿童", pinyin:"értóng", meaning:"child", example:"身高一米二以下的孩子，可以买儿童票。"},
  {word:"而", pinyin:"ér", meaning:"and; but; however", example:"我们都已经等了一个小时了，而他还没来。"},
  {word:"发生", pinyin:"fāshēng", meaning:"take place; happen", example:"情况发生了很大的变化。"},
  {word:"发展", pinyin:"fāzhǎn", meaning:"develop; expand", example:"这些年经济发展很快。"},
  {word:"法律", pinyin:"fǎlǜ", meaning:"law", example:"我在大学学习法律专业。"},
  {word:"翻译", pinyin:"fānyì", meaning:"translate", example:"请把这篇文章翻译成汉语。"},
  {word:"烦恼", pinyin:"fánnǎo", meaning:"vexation; worry", example:"生活中总会遇到一些烦恼。"},
  {word:"反对", pinyin:"fǎnduì", meaning:"be against; object to", example:"这个计划大家都反对。"},
  {word:"方法", pinyin:"fāngfǎ", meaning:"method; way", example:"我们一定能找到解决问题的方法。"},
  {word:"方面", pinyin:"fāngmiàn", meaning:"aspect", example:"爸爸喜欢看历史方面的书。"},
  {word:"方向", pinyin:"fāngxiàng", meaning:"direction", example:"是这个方向吗？我觉得我们迷路了。"},
  {word:"房东", pinyin:"fángdōng", meaning:"landlord", example:"我的房东很友好，经常帮助我。"},
  {word:"放弃", pinyin:"fàngqì", meaning:"give up", example:"我放弃了留学的机会。"},
  {word:"放暑假", pinyin:"fàng shǔjià", meaning:"have a summer vacation", example:"明天就要放暑假了。"},
  {word:"放松", pinyin:"fàngsōng", meaning:"relax", example:"考试结束了，我们需要放松一下。"},
  {word:"费用", pinyin:"fèiyòng", meaning:"expense; money spent", example:"咱们这个月的生活费用是多少？"},
  {word:"份", pinyin:"fèn", meaning:"part; portion", example:"我一个人吃了两份饭，太饿了。"},
  {word:"丰富", pinyin:"fēngfù", meaning:"abundant; enrich", example:"他是一位经验丰富的老师。"},
  {word:"否则", pinyin:"fǒuzé", meaning:"otherwise", example:"我们现在出发吧，否则会迟到的。"},
  {word:"符合", pinyin:"fúhé", meaning:"correspond with; conform to", example:"这个做法不符合我们的要求。"},
  {word:"父亲", pinyin:"fùqīn", meaning:"father", example:"我父亲今年八十三岁了。"},
  {word:"付款", pinyin:"fùkuǎn", meaning:"pay", example:"购物可以在网上付款。"},
  {word:"负责", pinyin:"fùzé", meaning:"be in charge of; responsible", example:"我们会对这件事负责。"},
  {word:"复印", pinyin:"fùyìn", meaning:"copy", example:"这份材料，请再复印两份。"},
  {word:"复杂", pinyin:"fùzá", meaning:"complicated; complex", example:"这个问题太复杂，我听不懂。"},
  {word:"富", pinyin:"fù", meaning:"rich", example:"人们的生活越来越富。"},
  {word:"改变", pinyin:"gǎibiàn", meaning:"change; vary", example:"我已经改变了计划。"},
  {word:"干杯", pinyin:"gānbēi", meaning:"cheers", example:"祝大家节日快乐，干杯！"},
  {word:"赶", pinyin:"gǎn", meaning:"catch; get", example:"快点儿，我们要赶不上火车了。"},
  {word:"敢", pinyin:"gǎn", meaning:"dare to do", example:"天太黑了，我不敢一个人出去。"},
  {word:"感动", pinyin:"gǎndòng", meaning:"move or touch sb; feel moved", example:"这个电影我看了很感动。"},
  {word:"感觉", pinyin:"gǎnjué", meaning:"feeling; sense", example:"看了这本书，你有什么感觉？"},
  {word:"感情", pinyin:"gǎnqíng", meaning:"feeling; emotion", example:"他的表演感情非常丰富。"},
  {word:"感谢", pinyin:"gǎnxiè", meaning:"thank; be grateful", example:"感谢您对我们的帮助。"},
  {word:"干", pinyin:"gàn", meaning:"do; work", example:"暑假你想去干什么？去旅游怎么样？"},
  {word:"高级", pinyin:"gāojí", meaning:"advanced", example:"这是一家很高级的饭店。"},
  {word:"高速公路", pinyin:"gāosùgōnglù", meaning:"expressway", example:"这里新修了一条高速公路。"},
  {word:"各", pinyin:"gè", meaning:"every", example:"超市里有各种水果。"},
  {word:"工资", pinyin:"gōngzī", meaning:"wage; pay; salary", example:"他的新工作工资很高。"},
  {word:"公里", pinyin:"gōnglǐ", meaning:"kilometer", example:"这两个城市之间的距离有300公里。"},
  {word:"功夫", pinyin:"gōngfu", meaning:"Kung Fu", example:"我最近在学习中国功夫。"},
  {word:"共同", pinyin:"gòngtóng", meaning:"common", example:"我和我妻子有共同的理想和生活目标。"},
  {word:"购物", pinyin:"gòuwù", meaning:"go shopping", example:"现在人们喜欢在网上购物。"},
  {word:"够", pinyin:"gòu", meaning:"enough", example:"电脑五千元，你带的钱够吗？"},
  {word:"估计", pinyin:"gūjì", meaning:"estimate", example:"我估计他们已经到了机场了。"},
  {word:"鼓励", pinyin:"gǔlì", meaning:"encourage; encouragement", example:"父母应该给孩子更多的鼓励。"},
  {word:"故意", pinyin:"gùyì", meaning:"intentionally", example:"对不起，我不是故意的。"},
  {word:"顾客", pinyin:"gùkè", meaning:"customer", example:"服务员热情地为顾客服务。"},
  {word:"挂", pinyin:"guà", meaning:"suspend; hang; hang up", example:"我们把画儿挂在墙上吧。"},
  {word:"关键", pinyin:"guānjiàn", meaning:"key point; crucial", example:"这不是问题的关键。"},
  {word:"观众", pinyin:"guānzhòng", meaning:"viewer; audience", example:"电视机前的观众朋友们，大家好。"},
  {word:"管理", pinyin:"guǎnlǐ", meaning:"be in charge of; manage", example:"现在是谁管理这座房子？"},
  {word:"光", pinyin:"guāng", meaning:"light; solely; used up", example:"早上打开窗户，太阳光照了进来。"},
  {word:"广播", pinyin:"guǎngbō", meaning:"broadcasting", example:"爷爷正在听广播。"},
  {word:"广告", pinyin:"guǎnggào", meaning:"advertisement", example:"我在报纸上看到了你们的广告。"},
  {word:"逛", pinyin:"guàng", meaning:"stroll; roam", example:"今天我陪妈妈去逛街了。"},
  {word:"规定", pinyin:"guīdìng", meaning:"stipulate; rule", example:"公司规定，不能来上班要先请假。"},
  {word:"国籍", pinyin:"guójí", meaning:"nationality", example:"请您在表格里填上国籍和姓名。"},
  {word:"国际", pinyin:"guójì", meaning:"international", example:"请问国际航班的出口在哪儿？"},
  {word:"果汁", pinyin:"guǒzhī", meaning:"juice", example:"我更爱喝我自己做的果汁。"},
  {word:"过程", pinyin:"guòchéng", meaning:"process; course", example:"在工作的过程中，我们可能会遇到很多问题。"},
  {word:"海洋", pinyin:"hǎiyáng", meaning:"ocean", example:"孩子们被海洋馆深深地吸引了。"},
  {word:"害羞", pinyin:"hàixiū", meaning:"shy", example:"她很害羞，不太喜欢说话。"},
  {word:"寒假", pinyin:"hánjià", meaning:"winter vacation", example:"我们再过一星期就要放寒假了。"},
  {word:"汗", pinyin:"hàn", meaning:"sweat", example:"我一吃饭就出汗。"},
  {word:"好处", pinyin:"hǎochu", meaning:"good point; advantage", example:"运动对身体健康有好处。"},
  {word:"好像", pinyin:"hǎoxiàng", meaning:"as if; seem", example:"天阴了，好像要下雨了。"},
  {word:"号码", pinyin:"hàomǎ", meaning:"number", example:"你还记得他的电话号码吗？"},
  {word:"合格", pinyin:"hégé", meaning:"qualified", example:"我是一名合格的律师。"},
  {word:"合适", pinyin:"héshì", meaning:"fit; suitable", example:"这双鞋你穿很合适。"},
  {word:"盒子", pinyin:"hézi", meaning:"box", example:"盒子里装了些什么？"},
  {word:"后悔", pinyin:"hòuhuǐ", meaning:"regret", example:"没去看演出，我很后悔。"},
  {word:"厚", pinyin:"hòu", meaning:"thick", example:"这本书太厚了。"},
  {word:"互联网", pinyin:"hùliánwǎng", meaning:"the Internet", example:"互联网给人们的生活带来了很多方便。"},
  {word:"互相", pinyin:"hùxiāng", meaning:"each other; one another", example:"我们是邻居，应该互相帮助。"},
  {word:"护士", pinyin:"hùshi", meaning:"nurse", example:"护士正在给病人打针。"},
  {word:"怀疑", pinyin:"huáiyí", meaning:"doubt; suspect", example:"我怀疑他忘了今天要开会。"},
  {word:"回忆", pinyin:"huíyì", meaning:"recall; memory", example:"我们经常回忆起小时候的事情。"},
  {word:"活动", pinyin:"huódòng", meaning:"take exercise; activity", example:"我去公园里活动活动。"},
  {word:"活泼", pinyin:"huópō", meaning:"lively", example:"妹妹是个活泼可爱的小女孩。"},
  {word:"火", pinyin:"huǒ", meaning:"fire; anger; popular", example:"森林着火了。"},
  {word:"获得", pinyin:"huòdé", meaning:"get; obtain", example:"祝贺你们获得了好成绩。"},
  {word:"积极", pinyin:"jījí", meaning:"positive; vigorous", example:"我们要用积极的态度面对生活。"},
  {word:"积累", pinyin:"jīlěi", meaning:"accumulate; accumulation", example:"他在工作中积累了丰富的经验。"},
  {word:"基础", pinyin:"jīchǔ", meaning:"basis; foundation; basic", example:"请在原来的基础上再改一改。"},
  {word:"激动", pinyin:"jīdòng", meaning:"excited; thrill", example:"看了这部电影，我很激动。"},
  {word:"及时", pinyin:"jíshí", meaning:"in time; just right", example:"谢谢你及时赶来帮助我。"},
  {word:"即使", pinyin:"jíshǐ", meaning:"even if", example:"即使遇到了困难也不要放弃。"},
  {word:"计划", pinyin:"jìhuà", meaning:"plan", example:"这个计划很不错，你就按照它去做吧。"},
  {word:"计算机", pinyin:"jìsuànjī", meaning:"computer", example:"每个教室里都有一台计算机。"},
  {word:"记者", pinyin:"jìzhě", meaning:"reporter; journalist", example:"一位记者报道了这个消息。"},
  {word:"技术", pinyin:"jìshù", meaning:"technology; technique", example:"这是一个复杂的技术问题。"},
  {word:"既然", pinyin:"jìrán", meaning:"since", example:"你既然答应了，就要把事情办好。"},
  {word:"继续", pinyin:"jìxù", meaning:"continue", example:"请大家休息一会儿，十分钟后继续上课。"},
  {word:"寄", pinyin:"jì", meaning:"mail", example:"你的信已经寄到。"},
  {word:"加班", pinyin:"jiābān", meaning:"work overtime", example:"这个星期，我们几乎每天都加班。"},
  {word:"加油站", pinyin:"jiāyóuzhàn", meaning:"gas station", example:"你家附近有加油站吗？"},
  {word:"家具", pinyin:"jiājù", meaning:"furniture", example:"搬家后我们换了新家具。"},
  {word:"价格", pinyin:"jiàgé", meaning:"price", example:"从去年开始，汽车的价格在降低。"},
  {word:"假", pinyin:"jiǎ", meaning:"fake; false", example:"做人要诚实，不能说假话。"},
  {word:"坚持", pinyin:"jiānchí", meaning:"insist on; persist in", example:"他一直坚持自己的看法。"},
  {word:"减肥", pinyin:"jiǎnféi", meaning:"lose weight", example:"我每天跑步减肥。"},
  {word:"减少", pinyin:"jiǎnshǎo", meaning:"reduce; decrease", example:"顾客减少了三分之一。"},
  {word:"建议", pinyin:"jiànyì", meaning:"suggest; suggestion", example:"我建议明天休息一天。"},
  {word:"将来", pinyin:"jiānglái", meaning:"in the future", example:"将来你打算做什么工作？"},
  {word:"奖金", pinyin:"jiǎngjīn", meaning:"prize; bonus", example:"我们年底发了一笔奖金。"},
  {word:"降低", pinyin:"jiàngdī", meaning:"lower; reduce", example:"秋天来了，温度开始降低了。"},
  {word:"交", pinyin:"jiāo", meaning:"give; hand over; make friends", example:"我已经把材料交给经理了。"},
  {word:"交流", pinyin:"jiāoliú", meaning:"communicate; exchange", example:"语言是人和人之间交流的工具。"},
  {word:"交通", pinyin:"jiāotōng", meaning:"traffic", example:"常用的交通工具有汽车、火车、飞机等。"},
  {word:"郊区", pinyin:"jiāoqū", meaning:"suburbs; outskirts", example:"我住在郊区，开车半个小时就能到市中心。"},
  {word:"骄傲", pinyin:"jiāo’ào", meaning:"proud", example:"获得了成功也不能太骄傲。"},
  {word:"饺子", pinyin:"jiǎozi", meaning:"jiaozi; dumpling", example:"中国人过春节要吃饺子。"},
  {word:"教授", pinyin:"jiàoshòu", meaning:"professor", example:"他是一位大学教授。"},
  {word:"教育", pinyin:"jiàoyù", meaning:"education; educate", example:"父母很重视孩子的教育。"},
  {word:"接受", pinyin:"jiēshòu", meaning:"accept; take up", example:"你的意见我都接受。"},
  {word:"接着", pinyin:"jiēzhe", meaning:"continue; go on", example:"他想了一会儿接着写。"},
  {word:"节", pinyin:"jié", meaning:"section; period of class", example:"我们下午只有一节课。"},
  {word:"节约", pinyin:"jiéyuē", meaning:"economize; save", example:"请节约用水。"},
  {word:"结果", pinyin:"jiéguǒ", meaning:"result", example:"你看比赛了吗，结果怎么样？"},
  {word:"解释", pinyin:"jiěshì", meaning:"explain; explanation", example:"他把原因解释得很清楚。"},
  {word:"尽管", pinyin:"jǐnguǎn", meaning:"although; even though", example:"尽管我认识他很久了，但是并不了解。"},
  {word:"紧张", pinyin:"jǐnzhāng", meaning:"feel nervous", example:"第一次演出，他很紧张。"},
  {word:"进行", pinyin:"jìnxíng", meaning:"execute; carry out", example:"比赛还在进行。"},
  {word:"禁止", pinyin:"jìnzhǐ", meaning:"forbid; prohibit", example:"公共场所禁止抽烟。"},
  {word:"京剧", pinyin:"jīngjù", meaning:"Beijing Opera", example:"她是一位著名的京剧演员。"},
  {word:"经济", pinyin:"jīngjì", meaning:"economy", example:"近些年来这个城市的经济发展很快。"},
  {word:"经历", pinyin:"jīnglì", meaning:"go through; experience", example:"这段时间，我经历了很多事情。"},
  {word:"经验", pinyin:"jīngyàn", meaning:"experience", example:"他在工作中积累了很多经验。"},
  {word:"精彩", pinyin:"jīngcǎi", meaning:"brilliant; wonderful", example:"你们的表演真精彩，大家都很喜欢。"},
  {word:"景色", pinyin:"jǐngsè", meaning:"scenery; view", example:"日落的时候，海边的景色很美。"},
  {word:"警察", pinyin:"jǐngchá", meaning:"policeman; policewoman", example:"我从小就想成为一名警察。"},
  {word:"竞争", pinyin:"jìngzhēng", meaning:"compete; contend", example:"运动员们在赛场上激烈地竞争。"},
  {word:"竟然", pinyin:"jìngrán", meaning:"unexpectedly", example:"他们竟然只用了一周就完成了任务。"},
  {word:"镜子", pinyin:"jìngzi", meaning:"mirror; glass", example:"对不起，我把镜子打破了。"},
  {word:"究竟", pinyin:"jiūjìng", meaning:"on earth", example:"你究竟为什么哭呢？"},
  {word:"举", pinyin:"jǔ", meaning:"lift; hold up", example:"大家还有问题吗？请举手。"},
  {word:"举办", pinyin:"jǔbàn", meaning:"hold (an exhibition, contest, etc.)", example:"这个活动由我们来举办。"},
  {word:"举行", pinyin:"jǔxíng", meaning:"perform; take place", example:"会议两点钟举行。"},
  {word:"拒绝", pinyin:"jùjué", meaning:"decline; reject", example:"他拒绝了大家的邀请。"},
  {word:"距离", pinyin:"jùlí", meaning:"be apart from; distance", example:"我家距离公司很远。"},
  {word:"聚会", pinyin:"jùhuì", meaning:"meeting; get-together", example:"明天有个聚会，你想参加吗？"},
  {word:"开玩笑", pinyin:"kāi wánxiào", meaning:"make a joke", example:"你是在开玩笑吧？"},
  {word:"开心", pinyin:"kāixīn", meaning:"happy; joyful", example:"妹妹开心地笑了。"},
  {word:"看法", pinyin:"kànfǎ", meaning:"opinion", example:"请说说您对这件事儿的看法吧。"},
  {word:"考虑", pinyin:"kǎolǜ", meaning:"think; consider", example:"我会认真考虑一下这个问题。"},
  {word:"科学", pinyin:"kēxué", meaning:"science", example:"他在学校里学习了很多科学知识。"},
  {word:"棵", pinyin:"kē", meaning:"used for plants", example:"这棵树又高又大。"},
  {word:"咳嗽", pinyin:"késou", meaning:"cough", example:"他感冒了，咳嗽得很厉害。"},
  {word:"可怜", pinyin:"kělián", meaning:"pitiful; pitiable", example:"这个小孩儿找不到家了，真可怜。"},
  {word:"可是", pinyin:"kěshì", meaning:"but; yet; however", example:"虽然我很想去，可是实在没时间。"},
  {word:"可惜", pinyin:"kěxī", meaning:"regrettable; unfortunate", example:"你不能来参加我们的聚会太可惜了。"},
  {word:"客厅", pinyin:"kètīng", meaning:"living room", example:"爸爸正在客厅看电视呢。"},
  {word:"肯定", pinyin:"kěndìng", meaning:"certainly; surely", example:"我五点以前肯定会回来。"},
  {word:"空", pinyin:"kōng", meaning:"empty; vacant", example:"盒子里是空的，什么都没有。"},
  {word:"空气", pinyin:"kōngqì", meaning:"air", example:"公园里空气非常新鲜。"},
  {word:"恐怕", pinyin:"kǒngpà", meaning:"perhaps; probably; maybe", example:"恐怕要下雨了，你带伞了吗？"},
  {word:"苦", pinyin:"kǔ", meaning:"bitter", example:"药太苦了，我不想吃。"},
  {word:"矿泉水", pinyin:"kuàngquánshuǐ", meaning:"mineral water", example:"我买了两瓶矿泉水。"},
  {word:"困", pinyin:"kùn", meaning:"feel sleepy", example:"我困了，要去睡觉。"},
  {word:"困难", pinyin:"kùnnan", meaning:"trouble; difficulty; difficult", example:"工作中，我们遇到了很多困难。"},
  {word:"垃圾桶", pinyin:"lājītǒng", meaning:"trash can", example:"街上有许多垃圾桶。"},
  {word:"拉", pinyin:"lā", meaning:"pull", example:"妈妈拉着女儿的手。"},
  {word:"辣", pinyin:"là", meaning:"spicy; hot", example:"我不习惯吃太辣的菜。"},
  {word:"来不及", pinyin:"láibují", meaning:"haven't enough time", example:"我今天早上起晚了，来不及吃早饭了。"},
  {word:"来得及", pinyin:"láidejí", meaning:"have enough time", example:"电影九点半才开始，还来得及。"},
  {word:"来自", pinyin:"láizì", meaning:"come from", example:"他来自一个美丽的海边城市。"},
  {word:"懒", pinyin:"lǎn", meaning:"lazy", example:"我家的小猫很懒，一个下午都在睡觉。"},
  {word:"浪费", pinyin:"làngfèi", meaning:"squander; waste", example:"这样做只是浪费时间。"},
  {word:"浪漫", pinyin:"làngmàn", meaning:"romantic", example:"这本书讲了一个浪漫的爱情故事。"},
  {word:"老虎", pinyin:"lǎohǔ", meaning:"tiger", example:"每次去动物园，儿子最喜欢看的就是老虎。"},
  {word:"冷静", pinyin:"lěngjìng", meaning:"calm; cool", example:"你十分冷静地面对这个问题。"},
  {word:"离婚", pinyin:"líhūn", meaning:"divorce", example:"我最近才知道他们离婚了。"},
  {word:"礼拜天", pinyin:"lǐbàitiān", meaning:"Sunday", example:"这个礼拜天，你有空吗？"},
  {word:"礼貌", pinyin:"lǐmào", meaning:"politeness; manners", example:"这个小朋友很有礼貌。"},
  {word:"理发", pinyin:"lǐfà", meaning:"get a haircut", example:"你什么时候去理发？"},
  {word:"理解", pinyin:"lǐjiě", meaning:"understand; comprehend", example:"这个问题你能理解了吗？"},
  {word:"理想", pinyin:"lǐxiǎng", meaning:"ideal; perfect", example:"每个人都有自己的理想。"},
  {word:"力气", pinyin:"lìqi", meaning:"strength; might", example:"走了这么多路，我累得一点儿力气都没有了。"},
  {word:"厉害", pinyin:"lìhai", meaning:"grave; serious; acute", example:"他病得很厉害，住院了。"},
  {word:"俩", pinyin:"liǎ", meaning:"pair; couple", example:"我们俩是好朋友。"},
  {word:"连", pinyin:"lián", meaning:"even; be in succession", example:"你怎么连我都忘了？"},
  {word:"联系", pinyin:"liánxì", meaning:"communicate; association", example:"有什么问题可以随时联系我。"},
  {word:"凉快", pinyin:"liángkuai", meaning:"cool", example:"秋天的天气很凉快。"},
  {word:"零钱", pinyin:"língqián", meaning:"change", example:"您可以帮我换一些零钱吗？"},
  {word:"另外", pinyin:"lìngwài", meaning:"in addition", example:"我还要跟你谈另外一件事情。"},
  {word:"留", pinyin:"liú", meaning:"stay", example:"我留下等他，你先走吧。"},
  {word:"流利", pinyin:"liúlì", meaning:"fluent", example:"你的汉语说得很流利。"},
  {word:"流行", pinyin:"liúxíng", meaning:"popular; fashionable", example:"很多年轻人都喜欢流行音乐。"},
  {word:"旅行", pinyin:"lǚxíng", meaning:"travel", example:"我们计划夏天去云南旅行。"},
  {word:"律师", pinyin:"lǜshī", meaning:"lawyer", example:"我的妈妈是一名律师。"},
  {word:"乱", pinyin:"luàn", meaning:"messy; disorderly", example:"房间里很乱，我们收拾一下吧。"},
  {word:"麻烦", pinyin:"máfan", meaning:"troublesome; bother", example:"这件事儿很麻烦，我们需要你的帮助。"},
  {word:"马虎", pinyin:"mǎhu", meaning:"careless; negligent", example:"做事要认真，不能这么马虎。"},
  {word:"满", pinyin:"mǎn", meaning:"filled; full of", example:"我的书包里装满了书。"},
  {word:"毛", pinyin:"máo", meaning:"hair; fur; tenth of one Yuan", example:"这只小狗的毛是白色的。"},
  {word:"毛巾", pinyin:"máojīn", meaning:"towel", example:"热了吧，用毛巾擦擦汗吧。"},
  {word:"美好", pinyin:"měihǎo", meaning:"bright; beautiful (abstract)", example:"我觉得每天的生活都很美好。"},
  {word:"美丽", pinyin:"měilì", meaning:"beautiful", example:"她真是一个美丽的女孩儿。"},
  {word:"梦", pinyin:"mèng", meaning:"dream", example:"这真是个有趣的梦！"},
  {word:"迷路", pinyin:"mílù", meaning:"get lost; lose one's way", example:"他在森林里迷路了。"},
  {word:"密码", pinyin:"mìmǎ", meaning:"code; password", example:"我把信用卡的密码忘了。"},
  {word:"免费", pinyin:"miǎnfèi", meaning:"free", example:"在这家饭店吃饭，饮料免费。"},
  {word:"秒", pinyin:"miǎo", meaning:"second", example:"哥哥跑100米只用了15秒。"},
  {word:"民族", pinyin:"mínzú", meaning:"nation; race; ethnic group", example:"中国是个多民族的国家。"},
  {word:"母亲", pinyin:"mǔqīn", meaning:"mother", example:"我来介绍一下，这位是我的母亲。"},
  {word:"目的", pinyin:"mùdì", meaning:"purpose; aim", example:"我不明白他这样做的目的。"},
  {word:"内", pinyin:"nèi", meaning:"inner; inside", example:"包括张老师在内，教室里一共有10个人。"},
  {word:"内容", pinyin:"nèiróng", meaning:"content; substance", example:"这篇文章的内容非常精彩。"},
  {word:"耐心", pinyin:"nàixīn", meaning:"patience", example:"教育孩子要有耐心。"},
  {word:"难道", pinyin:"nándào", meaning:"used in a rhetorical question", example:"这些菜难道不好吃吗？"},
  {word:"难受", pinyin:"nánshòu", meaning:"feel unwell; suffer pain", example:"我感冒了，身体很难受。"},
  {word:"能力", pinyin:"nénglì", meaning:"ability; capacity", example:"每个人都有自己的能力和特点。"},
  {word:"年龄", pinyin:"niánlíng", meaning:"age", example:"随便问别人的年龄是不礼貌的。"},
  {word:"弄", pinyin:"nòng", meaning:"do; manage; handle", example:"小狗把房间弄得很乱。"},
  {word:"暖和", pinyin:"nuǎnhuo", meaning:"warm", example:"春天来了，天气变暖和了。"},
  {word:"偶尔", pinyin:"ǒu'ěr", meaning:"once in a while; occasionally", example:"我偶尔会在学校见到她。"},
  {word:"排队", pinyin:"páiduì", meaning:"line up", example:"请大家排队，不要挤。"},
  {word:"排列", pinyin:"páiliè", meaning:"arrange; rank", example:"请把这些盒子按照从大到小的顺序排列。"},
  {word:"排球", pinyin:"páiqiú", meaning:"volleyball", example:"我加入了学校的排球队。"},
  {word:"判断", pinyin:"pànduàn", meaning:"decision; judgement", example:"你的判断完全正确。"},
  {word:"陪", pinyin:"péi", meaning:"accompany; keep company", example:"在我伤心的时候，你总是陪在我身边。"},
  {word:"批评", pinyin:"pīpíng", meaning:"criticize; criticism", example:"老师很少会批评我。"},
  {word:"皮肤", pinyin:"pífū", meaning:"skin", example:"妈妈很注意保护皮肤。"},
  {word:"脾气", pinyin:"píqi", meaning:"temper; disposition", example:"他脾气好，从来不发火。"},
  {word:"篇", pinyin:"piān", meaning:"used for essays, articles, etc.", example:"这篇报道是我写的。"},
  {word:"骗", pinyin:"piàn", meaning:"deceive; cheat", example:"我没骗你，他真的来了。"},
  {word:"乒乓球", pinyin:"pīngpāngqiú", meaning:"table tennis; ping-pong", example:"有谁想参加乒乓球比赛？"},
  {word:"平时", pinyin:"píngshí", meaning:"normally; usually", example:"她平时很少运动。"},
  {word:"瓶子", pinyin:"píngzi", meaning:"bottle", example:"瓶子里还有水吗？"},
  {word:"破", pinyin:"pò", meaning:"broken; damaged", example:"这个袋子已经破了，请帮我换一个。"},
  {word:"葡萄", pinyin:"pútao", meaning:"grape", example:"葡萄五元一斤。"},
  {word:"普遍", pinyin:"pǔbiàn", meaning:"universal; general", example:"这是大家普遍反映的一个问题。"},
  {word:"其次", pinyin:"qícì", meaning:"secondly; next; then", example:"内容是最主要的，其次才是形式。"},
  {word:"其中", pinyin:"qízhōng", meaning:"among; in; inside", example:"我买的水果很多，其中包括葡萄。"},
  {word:"起来", pinyin:"qǐlái", meaning:"used after a verb to indicate direction", example:"他的心情好起来了。"},
  {word:"气候", pinyin:"qìhòu", meaning:"climate", example:"你能适应北方的气候吗？"},
  {word:"千万", pinyin:"qiānwàn", meaning:"however; anyhow; in any case", example:"你千万别忘了明天的会议。"},
  {word:"签证", pinyin:"qiānzhèng", meaning:"visa", example:"我需要到大使馆去办签证。"},
  {word:"敲", pinyin:"qiāo", meaning:"knock; beat; strike", example:"有人敲门，你去看看谁来了。"},
  {word:"桥", pinyin:"qiáo", meaning:"bridge", example:"河上有一座小桥。"},
  {word:"巧克力", pinyin:"qiǎokèlì", meaning:"chocolate", example:"我最爱吃巧克力了。"},
  {word:"亲戚", pinyin:"qīnqi", meaning:"kinsfolk; relative", example:"我的亲戚大多住在北京。"},
  {word:"轻", pinyin:"qīng", meaning:"light", example:"这件衣服很轻，但是很暖和。"},
  {word:"轻松", pinyin:"qīngsōng", meaning:"light; relaxed; relax", example:"这个工作对他来说并不轻松。"},
  {word:"情况", pinyin:"qíngkuàng", meaning:"circumstance; situation", example:"她最了解公司的情况了。"},
  {word:"请假", pinyin:"qǐngjià", meaning:"ask for leave", example:"我生病了，所以需要请假。"},
  {word:"穷", pinyin:"qióng", meaning:"poor; poverty-stricken", example:"这位老人虽然很穷，但是生活得很快乐。"},
  {word:"区别", pinyin:"qūbié", meaning:"difference", example:"这两种材料有什么区别吗？"},
  {word:"取", pinyin:"qǔ", meaning:"take; get", example:"今天下午我要去银行取钱。"},
  {word:"全部", pinyin:"quánbù", meaning:"whole; all", example:"同学们全部都来了。"},
  {word:"缺点", pinyin:"quēdiǎn", meaning:"defect; drawback; fault", example:"每个人身上都有优点和缺点。"},
  {word:"缺少", pinyin:"quēshǎo", meaning:"lack; be short of", example:"你看还缺少什么，我现在就去买。"},
  {word:"却", pinyin:"què", meaning:"but; yet; however; while", example:"我有很多话要说，可是一紧张却说不出来了。"},
  {word:"确实", pinyin:"quèshí", meaning:"really; indeed", example:"你最近确实很有进步。"},
  {word:"然而", pinyin:"rán'ér", meaning:"yet; but; however", example:"我花了很多时间来读这本书，然而一直没有读懂。"},
  {word:"热闹", pinyin:"rènao", meaning:"lively; bustling with noise and excitement", example:"大街上非常热闹。"},
  {word:"任何", pinyin:"rènhé", meaning:"any; whichever; whatever", example:"妈妈比任何人都了解我。"},
  {word:"任务", pinyin:"rènwu", meaning:"assignment; mission; task", example:"他很快就能完成这个任务。"},
  {word:"扔", pinyin:"rēng", meaning:"throw away; cast aside", example:"请把垃圾扔到垃圾桶里。"},
  {word:"仍然", pinyin:"réngrán", meaning:"still; yet", example:"今天仍然是个好天气。"},
  {word:"日记", pinyin:"rìjì", meaning:"diary; journal", example:"女儿养成了每天写日记的习惯。"},
  {word:"入口", pinyin:"rùkǒu", meaning:"entrance; entry", example:"我在大楼的入口等你。"},
  {word:"散步", pinyin:"sànbù", meaning:"take a walk; go for a walk", example:"晚饭后，我们经常出去散步。"},
  {word:"森林", pinyin:"sēnlín", meaning:"forest", example:"山上有一大片森林。"},
  {word:"沙发", pinyin:"shāfā", meaning:"sofa; upholstered arm chair", example:"请在沙发上坐一会儿，我去给您倒杯茶。"},
  {word:"伤心", pinyin:"shāngxīn", meaning:"sad; grieved", example:"听到这个消息后，我很伤心。"},
  {word:"商量", pinyin:"shāngliang", meaning:"consult; discuss; talk over", example:"这件事儿要先和家人商量一下。"},
  {word:"稍微", pinyin:"shāowēi", meaning:"a little; bit; slightly", example:"稍微一马虎就会出错。"},
  {word:"勺子", pinyin:"sháozi", meaning:"spoon; scoop; ladle", example:"不好意思，我把勺子掉在地上了。"},
  {word:"社会", pinyin:"shèhuì", meaning:"society", example:"这些社会问题大家都很关心。"},
  {word:"申请", pinyin:"shēnqǐng", meaning:"apply for; ask for", example:"我向银行申请了一张信用卡。"},
  {word:"深", pinyin:"shēn", meaning:"deep", example:"这条河很深，有一百多米。"},
  {word:"甚至", pinyin:"shènzhì", meaning:"even; so far as to", example:"大家玩儿得很开心，甚至忘了时间。"},
  {word:"生活", pinyin:"shēnghuó", meaning:"life; livelihood", example:"他是一个热爱生活的人。"},
  {word:"生命", pinyin:"shēngmìng", meaning:"life", example:"他把艺术看得比自己的生命更重要。"},
  {word:"生意", pinyin:"shēngyi", meaning:"business; trade", example:"他的生意越做越大。"},
  {word:"省", pinyin:"shěng", meaning:"province", example:"我来自山东省。"},
  {word:"剩", pinyin:"shèng", meaning:"be left over; remain", example:"大家都走了，只剩下他一个人。"},
  {word:"失败", pinyin:"shībài", meaning:"be defeated; lose; failure", example:"这次比赛，我们又失败了。"},
  {word:"失望", pinyin:"shīwàng", meaning:"lose hope; disappointed", example:"大家不要失望，我们还是有希望的。"},
  {word:"师傅", pinyin:"shīfu", meaning:"used to address strangers (like 'mister')", example:"师傅，请问电影院怎么走？"},
  {word:"十分", pinyin:"shífēn", meaning:"very; fully; extremely", example:"我对今天的演出十分满意。"},
  {word:"实际", pinyin:"shíjì", meaning:"real; actual", example:"他用一个实际的例子来说明这个问题。"},
  {word:"实在", pinyin:"shízài", meaning:"true; real; honest; indeed", example:"这个人很实在，值得信任。"},
  {word:"使", pinyin:"shǐ", meaning:"make; cause; enable", example:"他的话使我很感动。"},
  {word:"使用", pinyin:"shǐyòng", meaning:"use", example:"中国人吃饭一般使用筷子。"},
  {word:"世纪", pinyin:"shìjì", meaning:"century", example:"现在是二十一世纪了。"},
  {word:"是否", pinyin:"shìfǒu", meaning:"whether or not", example:"他是否能来，我还不太清楚。"},
  {word:"适合", pinyin:"shìhé", meaning:"suit; fit; be appropriate for", example:"我不太适合穿绿色的衣服。"},
  {word:"适应", pinyin:"shìyìng", meaning:"adjust; adapt; fit", example:"我已经适应这里的工作环境了。"},
  {word:"收", pinyin:"shōu", meaning:"receive; accept", example:"我收到你的信了。"},
  {word:"收入", pinyin:"shōurù", meaning:"income; revenue", example:"他每年有20万的收入。"},
  {word:"收拾", pinyin:"shōushi", meaning:"put in order; tidy; clear away", example:"我在收拾行李呢。"},
  {word:"首都", pinyin:"shǒudū", meaning:"capital (of a country)", example:"中国的首都是北京。"},
  {word:"首先", pinyin:"shǒuxiān", meaning:"first of all", example:"首先要休息好，然后才能工作好。"},
  {word:"受不了", pinyin:"shòubuliǎo", meaning:"can't bear; can't stand", example:"这里太吵了，真让人受不了。"},
  {word:"受到", pinyin:"shòudào", meaning:"accept; receive", example:"他的小说受到了读者们的欢迎。"},
  {word:"售货员", pinyin:"shòuhuòyuán", meaning:"shop assistant; salesclerk", example:"我在商场做售货员。"},
  {word:"输", pinyin:"shū", meaning:"lose; be beaten; be defeated", example:"这次比赛，我们输了。"},
  {word:"熟悉", pinyin:"shúxī", meaning:"know well; be familiar with", example:"我很熟悉这里的路，不会迷路的。"},
  {word:"数量", pinyin:"shùliàng", meaning:"amount; quantity", example:"这几个月来，顾客的数量在不断增加。"},
  {word:"数字", pinyin:"shùzì", meaning:"figure; numeral; number", example:"请把数字写清楚。"},
  {word:"帅", pinyin:"shuài", meaning:"handsome; graceful (for a man)", example:"小王是我们班最帅的男生。"},
  {word:"顺便", pinyin:"shùnbiàn", meaning:"conveniently; without extra effort", example:"下班的路上，我顺便买了些菜。"},
  {word:"顺利", pinyin:"shùnlì", meaning:"smooth; without a hitch", example:"比赛进行得很顺利。"},
  {word:"顺序", pinyin:"shùnxù", meaning:"order; sequence; succession", example:"请不要把顺序弄乱了。"},
  {word:"说明", pinyin:"shuōmíng", meaning:"explain; illustrate; show", example:"他把这件事的原因给大家说明了一下。"},
  {word:"硕士", pinyin:"shuòshì", meaning:"master's degree", example:"我在大学里读硕士研究生。"},
  {word:"死", pinyin:"sǐ", meaning:"die", example:"这棵树已经死了。"},
  {word:"速度", pinyin:"sùdù", meaning:"speed", example:"他跑步的速度真快！"},
  {word:"塑料袋", pinyin:"sùliàodài", meaning:"plastic bag", example:"为了保护环境，请不要使用塑料袋。"},
  {word:"酸", pinyin:"suān", meaning:"sour; tingle; ache", example:"你买的葡萄有点儿酸。"},
  {word:"随便", pinyin:"suíbiàn", meaning:"casual; random; informal", example:"大家请随便坐吧。"},
  {word:"随着", pinyin:"suízhe", meaning:"along with; in the wake of", example:"随着经济的发展，人们的生活有了很大的提高。"},
  {word:"孙子", pinyin:"sūnzi", meaning:"grandson", example:"爷爷非常喜欢自己的孙子。"},
  {word:"所有", pinyin:"suǒyǒu", meaning:"all", example:"所有的人都认为是他不对。"},
  {word:"台", pinyin:"tái", meaning:"used for machines", example:"这台电脑是新买的。"},
  {word:"抬", pinyin:"tái", meaning:"lift; raise; move; carry", example:"他们把课桌抬到教室里去了。"},
  {word:"态度", pinyin:"tàidu", meaning:"manner; attitude", example:"服务员对顾客的态度非常好。"},
  {word:"谈", pinyin:"tán", meaning:"talk; speak; chat; discuss", example:"他们两个人谈得很高兴。"},
  {word:"弹钢琴", pinyin:"tán gāngqín", meaning:"play the piano", example:"我四岁开始学习弹钢琴。"},
  {word:"汤", pinyin:"tāng", meaning:"soup", example:"您想再喝一碗汤吗？"},
  {word:"糖", pinyin:"táng", meaning:"sugar; candy", example:"我想吃块儿糖。"},
  {word:"躺", pinyin:"tǎng", meaning:"lie down; recline", example:"她躺在床上睡着了。"},
  {word:"趟", pinyin:"tàng", meaning:"time (of walk or trip)", example:"上个月我去了一趟北京。"},
  {word:"讨论", pinyin:"tǎolùn", meaning:"discuss; discussion", example:"我们开会讨论一下吧。"},
  {word:"讨厌", pinyin:"tǎoyàn", meaning:"be tired of; dislike; disagreeable", example:"我讨厌在饭馆吃饭。"},
  {word:"特点", pinyin:"tèdiǎn", meaning:"characteristic; distinguishing feature", example:"每个人都有自己的特点。"},
  {word:"提", pinyin:"tí", meaning:"tote; put forward; raise; mention", example:"爸爸手里提着一个行李箱。"},
  {word:"提供", pinyin:"tígōng", meaning:"give; provide; supply; offer", example:"图书馆为大家提供了安静的阅读环境。"},
  {word:"提前", pinyin:"tíqián", meaning:"in advance; advance the date", example:"我们提前完成了任务。"},
  {word:"提醒", pinyin:"tíxǐng", meaning:"remind; warn; call attention to", example:"我已经提醒过他，但他还是忘了。"},
  {word:"填空", pinyin:"tiánkòng", meaning:"fill in the blanks", example:"这是一道填空题。"},
  {word:"条件", pinyin:"tiáojiàn", meaning:"requirement; prerequisite; qualification", example:"她很符合我们的招聘条件。"},
  {word:"停", pinyin:"tíng", meaning:"stop", example:"汽车停了下来。"},
  {word:"挺", pinyin:"tǐng", meaning:"very; quite; pretty; rather", example:"这本书挺好看的。"},
  {word:"通过", pinyin:"tōngguò", meaning:"pass through; by means of; adopt", example:"汽车正在通过一座大桥。"},
  {word:"通知", pinyin:"tōngzhī", meaning:"inform; give notice; notice", example:"请通知大家来开会。"},
  {word:"同情", pinyin:"tóngqíng", meaning:"sympathize; show sympathy", example:"我都很同情他。"},
  {word:"推", pinyin:"tuī", meaning:"push", example:"我的车坏了，请帮我推一下好吗？"},
  {word:"推迟", pinyin:"tuīchí", meaning:"put off; postpone; defer", example:"飞机起飞的时间，推迟了20分钟。"},
  {word:"脱", pinyin:"tuō", meaning:"take off; strip; cast off", example:"房间很暖和，把大衣脱了吧。"},
  {word:"袜子", pinyin:"wàzi", meaning:"sock; stocking", example:"我把袜子洗干净了。"},
  {word:"完全", pinyin:"wánquán", meaning:"completely; absolutely; entirely", example:"我完全没想到他竟然是这样的人。"},
  {word:"网球", pinyin:"wǎngqiú", meaning:"tennis", example:"我最近才开始学习打网球。"},
  {word:"网站", pinyin:"wǎngzhàn", meaning:"website", example:"我想办一个汉语学习网站。"},
  {word:"往", pinyin:"wǎng", meaning:"to; toward", example:"再往前走500米就到了。"},
  {word:"往往", pinyin:"wǎngwǎng", meaning:"always", example:"星期天，他往往去公园散步。"},
  {word:"危险", pinyin:"wēixiǎn", meaning:"dangerous; hazardous", example:"在森林里吸烟很危险，容易着火。"},
  {word:"卫生间", pinyin:"wèishēngjiān", meaning:"toilet; bathroom; lavatory", example:"请问，卫生间在哪儿？"},
  {word:"味道", pinyin:"wèidào", meaning:"flavor; taste; savour", example:"我最爱吃妈妈做的鱼，味道好极了！"},
  {word:"温度", pinyin:"wēndù", meaning:"temperature", example:"进入冬季，温度越来越低。"},
  {word:"文章", pinyin:"wénzhāng", meaning:"essay; article", example:"她把旅行的经历写成了文章。"},
  {word:"污染", pinyin:"wūrǎn", meaning:"contaminate; pollute; taint", example:"现在环境污染越来越严重。"},
  {word:"无", pinyin:"wú", meaning:"have not; there be not", example:"他的话是无根据的。"},
  {word:"无聊", pinyin:"wúliáo", meaning:"boring; dull; uninteresting", example:"周末我一个人在家，很无聊。"},
  {word:"无论", pinyin:"wúlùn", meaning:"no matter what, how, etc.; regardless of", example:"无论我怎么解释，他都不明白。"},
  {word:"误会", pinyin:"wùhuì", meaning:"misunderstand; misunderstanding", example:"对不起，我误会你了。"},
  {word:"西红柿", pinyin:"xīhóngshì", meaning:"tomato", example:"我买了一些西红柿。"},
  {word:"吸引", pinyin:"xīyǐn", meaning:"attract; fascinate; arrest", example:"这部电影很吸引人。"},
  {word:"咸", pinyin:"xián", meaning:"salty", example:"盐放多了，菜有点儿咸。"},
  {word:"现金", pinyin:"xiànjīn", meaning:"cash", example:"我带的现金不太多，但是商店可以刷卡。"},
  {word:"羡慕", pinyin:"xiànmù", meaning:"admire; envy", example:"我很羡慕他有一份好工作。"},
  {word:"相反", pinyin:"xiāngfǎn", meaning:"opposite; contrary", example:"你说的跟我理解的正好相反。"},
  {word:"相同", pinyin:"xiāngtóng", meaning:"same", example:"你的自行车跟我的完全相同。"},
  {word:"香", pinyin:"xiāng", meaning:"delicious", example:"你做的菜真香啊！"},
  {word:"详细", pinyin:"xiángxì", meaning:"detailed; minute; careful", example:"她做的计划非常详细。"},
  {word:"响", pinyin:"xiǎng", meaning:"make a sound", example:"你听，是不是电话响了？"},
  {word:"橡皮", pinyin:"xiàngpí", meaning:"eraser", example:"你可以借我橡皮用一下吗？"},
  {word:"消息", pinyin:"xiāoxi", meaning:"information; news; tidings", example:"我给大家带来了一个好消。"},
  // ... continued from 1073 消息
  {word:"小吃", pinyin:"xiǎochī", meaning:"snack; refreshment", example:"来北京一定要尝一尝北京的小吃。"},
  {word:"小说", pinyin:"xiǎoshuō", meaning:"novel; fiction", example:"他在写一本小说，还没写完。"},
  {word:"效果", pinyin:"xiàoguǒ", meaning:"effect; result; outcome; purpose; impression", example:"这种感冒药的效果很好。"},
  {word:"笑话", pinyin:"xiàohua", meaning:"n. joke; v. laugh at; mock", example:"你讲的笑话真有意思。"},
  {word:"心情", pinyin:"xīnqíng", meaning:"mood; frame of mind; temper", example:"你今天看起来心情不错。"},
  {word:"辛苦", pinyin:"xīnkǔ", meaning:"hard; toilsome; painstaking", example:"爸爸的工作很辛苦。"},
  {word:"信封", pinyin:"xìnfēng", meaning:"envelope", example:"他把写好的信放进了信封里。"},
  {word:"信息", pinyin:"xìnxī", meaning:"information; news", example:"电视里报道了关于这件事的最新信息。"},
  {word:"信心", pinyin:"xìnxīn", meaning:"confidence; faith; reliance; assurance", example:"我们对你很有信心，你一定能行。"},
  {word:"兴奋", pinyin:"xīngfèn", meaning:"excited", example:"孩子们听说要去春游，都兴奋地跳了起来。"},
  {word:"行", pinyin:"xíng", meaning:"Ok! All right! No problem!", example:"甲：我们一起去看电影，好吗？乙：行，没问题。"},
  {word:"醒", pinyin:"xǐng", meaning:"wake; wake up", example:"我昨天夜里3点就醒了，然后就再也睡不着了。"},
  {word:"幸福", pinyin:"xìngfú", meaning:"adj. happy; n. well-being; happiness; bliss", example:"我生活得很幸福。"},
  {word:"性别", pinyin:"xìngbié", meaning:"gender; sex", example:"请在表格的第二行填写性别。"},
  {word:"性格", pinyin:"xìnggé", meaning:"character; nature; temperament; disposition", example:"我妻子的性格非常好，从不发脾气。"},
  {word:"修理", pinyin:"xiūlǐ", meaning:"mend; repair", example:"门坏了，我们找人来修理一下吧。"},
  {word:"许多", pinyin:"xǔduō", meaning:"many; much; great deal of; a lot of; numerous", example:"我们有许多年没见了。"},
  {word:"压力", pinyin:"yālì", meaning:"pressure; strain; stress; weight", example:"他最近工作压力很大。"},
  {word:"牙膏", pinyin:"yágāo", meaning:"toothpaste", example:"牙膏用完了，明天去买吧。"},
  {word:"亚洲", pinyin:"Yàzhōu", meaning:"Asia", example:"中国是亚洲国家。"},
  {word:"呀", pinyin:"ya", meaning:"mp. used at the end of a sentence; int. exclamation to show surprise", example:"你本来说好要来的呀。呀, 下雪了！"},
  {word:"严格", pinyin:"yángé", meaning:"strict; rigorous; stringent", example:"老师对我们的要求很严格。"},
  {word:"严重", pinyin:"yánzhòng", meaning:"grave; serious; acute", example:"他生病了，而且很严重。"},
  {word:"研究", pinyin:"yánjiū", meaning:"investigate; examine; go into", example:"这个问题我们还要再研究一下。"},
  {word:"盐", pinyin:"yán", meaning:"salt", example:"汤不咸，还是再放点儿盐吧。"},
  {word:"眼镜", pinyin:"yǎnjìng", meaning:"glasses; spectacles", example:"他戴这个黑色眼镜。"},
  {word:"演出", pinyin:"yǎnchū", meaning:"performance; presentation", example:"今天是为我们的第一次演出。"},
  {word:"演员", pinyin:"yǎnyuán", meaning:"actor or actress", example:"她是个著名的电影演员。"},
  {word:"阳光", pinyin:"yángguāng", meaning:"sunshine; sunlight", example:"阳光从窗户里进到房间里来。"},
  {word:"养成", pinyin:"yǎngchéng", meaning:"form; cultivate", example:"我从小就养成这个习惯。"},
  {word:"样子", pinyin:"yàngzi", meaning:"appearance; shape; form", example:"这件衣服的样子很不错。"},
  {word:"邀请", pinyin:"yāoqǐng", meaning:"invite; call on; send an invitation", example:"他邀请周末去他家做客。"},
  {word:"要是", pinyin:"yàoshì", meaning:"if", example:"你要是先来了，就等一下我。"},
  {word:"钥匙", pinyin:"yàoshi", meaning:"key (to a lock)", example:"我今天忘记带钥匙。"},
  {word:"也许", pinyin:"yěxǔ", meaning:"probably; perhaps; may; maybe; possibly", example:"他也许不会来了。"},
  {word:"叶子", pinyin:"yèzi", meaning:"leaf (of a plant)", example:"春天来了，小树新长出了叶子。"},
  {word:"页", pinyin:"yè", meaning:"page", example:"请打开书，翻到201页。"},
  {word:"一切", pinyin:"yíqiè", meaning:"all; every", example:"家里一切的事情，都是妈妈负责。"},
  {word:"以", pinyin:"yǐ", meaning:"using; taking; by means of", example:"他以这些标准来要求自己。"},
  {word:"以为", pinyin:"yǐwéi", meaning:"think or believe; feel; suppose; assume", example:"我以为你已经走了。"},
  {word:"艺术", pinyin:"yìshù", meaning:"art", example:"我对艺术非常感兴趣。"},
  {word:"意见", pinyin:"yìjiàn", meaning:"view; suggestion; opinion; idea", example:"你有什么意见，请说出来吧。"},
  {word:"因此", pinyin:"yīncǐ", meaning:"therefore; for this reason; consequently; hence; so", example:"他从小热爱音乐，因此长大后做了一名音乐老师。"},
  {word:"引起", pinyin:"yǐnqǐ", meaning:"bring; cause; lead to; give rise to; bring about; come of; arise from", example:"这件事引起了大家的不满。"},
  {word:"印象", pinyin:"yìnxiàng", meaning:"impression; effect; feeling", example:"他给我留下了很好的印象。"},
  {word:"赢", pinyin:"yíng", meaning:"win", example:"昨天的足球比赛，谁赢了？"},
  {word:"应聘", pinyin:"yìngpìn", meaning:"employed by", example:"他应聘到这所大学教书。"},
  {word:"永远", pinyin:"yǒngyuǎn", meaning:"forever; perpetually", example:"我永远不会忘记你对我的帮助。"},
  {word:"勇敢", pinyin:"yǒnggǎn", meaning:"brave; courageous", example:"哥哥是一个很勇敢的人。"},
  {word:"优点", pinyin:"yōudiǎn", meaning:"merit; advantage; virtue; excellence", example:"人不能拿自己的缺点和别人的优点比较。"},
  {word:"优秀", pinyin:"yōuxiù", meaning:"outstanding; great; superior; exceptional", example:"他是一个非常优秀的医生。"},
  {word:"幽默", pinyin:"yōumò", meaning:"humorous; funny", example:"李教授说话非常幽默。"},
  {word:"尤其", pinyin:"yóuqí", meaning:"especially; particularly; above all; least of all; by far; of all things; in particular", example:"他喜欢画画，尤其是画国画。"},
  {word:"由", pinyin:"yóu", meaning:"from", example:"这次航班由北京飞往杭州。"},
  {word:"由于", pinyin:"yóuyú", meaning:"owing to; as a result of; due to; in virtue of", example:"由于他工作认真，因此得到了大家的信任。"},
  {word:"邮局", pinyin:"yóujú", meaning:"post office", example:"邮局早上9点开门。"},
  {word:"友好", pinyin:"yǒuhǎo", meaning:"friendly; amicable", example:"我喜欢这个城市主要是因为这里的人非常友好。"},
  {word:"友谊", pinyin:"yǒuyì", meaning:"friendship; companionship; fellowship", example:"我们之间有很深的友谊。"},
  {word:"有趣", pinyin:"yǒuqù", meaning:"interesting; fascinating; amusing; funny", example:"你讲的这个故事真有趣！"},
  {word:"于是", pinyin:"yúshì", meaning:"as a result; therefore; whereupon", example:"我有事想问他，于是给他打了电话。"},
  {word:"愉快", pinyin:"yúkuài", meaning:"happy; pleased; joyful", example:"祝你周末愉快！"},
  {word:"与", pinyin:"yǔ", meaning:"with; to", example:"他很自信，喜欢与人竞争。"},
  {word:"羽毛球", pinyin:"yǔmáoqiú", meaning:"badminton", example:"你经常打羽毛球吗？"},
  {word:"语法", pinyin:"yǔfǎ", meaning:"grammar", example:"学习一门语言，需要对它的语法有一些了解。"},
  {word:"语言", pinyin:"yǔyán", meaning:"language", example:"语言是表达思想的工具。"},
  {word:"预习", pinyin:"yùxí", meaning:"preview", example:"请大家好好预习一下课文。"},
  {word:"原来", pinyin:"yuánlái", meaning:"former; original", example:"我还住在原来的地方。"},
  {word:"原谅", pinyin:"yuánliàng", meaning:"forgive; excuse; pardon", example:"请原谅我刚才说的话。"},
  {word:"原因", pinyin:"yuányīn", meaning:"reason; cause", example:"我已经找出问题的原因了。"},
  {word:"约会", pinyin:"yuēhuì", meaning:"sv. date; appointment; n. date; appointment", example:"她开始和小李约会了。今天晚上我有个约会。"},
  {word:"阅读", pinyin:"yuèdú", meaning:"read", example:"我正在阅读这本小说。"},
  {word:"云", pinyin:"yún", meaning:"cloud", example:"天上的云越来越多。"},
  {word:"允许", pinyin:"yǔnxǔ", meaning:"agree; permit; allow; let", example:"请允许我做一下自我介绍。"},
  {word:"杂志", pinyin:"zázhì", meaning:"magazine", example:"这本杂志上的文章都写得很好。"},
  {word:"咱们", pinyin:"zánmen", meaning:"we or us (inclusive of person or people spoken to)", example:"你来得正好，咱们商量一下。"},
  {word:"暂时", pinyin:"zànshí", meaning:"temporarily", example:"他把车暂时停在了路边。"},
  {word:"脏", pinyin:"zāng", meaning:"dirty", example:"我不小心把衣服弄脏了。"},
  {word:"责任", pinyin:"zérèn", meaning:"duty; responsibility", example:"这件事情，我们大家都有责任。"},
  {word:"增加", pinyin:"zēngjiā", meaning:"increase", example:"今年学校的人数从800增加到了1000。"},
  {word:"占线", pinyin:"zhànxiàn", meaning:"The line is busy.", example:"我连着打了几次，他的电话都占线。"},
  {word:"招聘", pinyin:"zhāopìn", meaning:"recruit and employ through advertisement and examination", example:"网站上有很多招聘信息。"},
  {word:"照", pinyin:"zhào", meaning:"look (into the mirror)", example:"她照了一下镜子，发现自己头发很乱。"},
  {word:"真正", pinyin:"zhēnzhèng", meaning:"genuine; true; real", example:"真正的朋友会在你遇到困难的时候帮助你。"},
  {word:"整理", pinyin:"zhěnglǐ", meaning:"put in order; arrange", example:"请把桌子上的书整理一下。"},
  {word:"正常", pinyin:"zhèngcháng", meaning:"normal; regular", example:"修理之后，我的电脑又能正常工作了。"},
  {word:"正好", pinyin:"zhènghǎo", meaning:"suitable", example:"这个帽子我戴正好，不大也不小。"},
  {word:"正确", pinyin:"zhèngquè", meaning:"right; correct; proper", example:"你的答案非常正确。"},
  {word:"正式", pinyin:"zhèngshì", meaning:"formal; official; regular", example:"现在比赛正式开始。"},
  {word:"证明", pinyin:"zhèngmíng", meaning:"prove; manifest; bear witness to", example:"事实证明，你是对的。"},
  {word:"之", pinyin:"zhī", meaning:"auxiliary word, used to form a grammatical structure", example:"我一个月之前见过他。"},
  {word:"支持", pinyin:"zhīchí", meaning:"v. assist; support; stand for; back up; n. support; assistance", example:"我们两个要互相支持。他从朋友那里得到了很多支持。"},
  {word:"知识", pinyin:"zhīshi", meaning:"knowledge", example:"我在阅读中获得了很多知识。"},
  {word:"直接", pinyin:"zhíjiē", meaning:"direct; immediate", example:"下班后，他直接回家了。"},
  {word:"值得", pinyin:"zhídé", meaning:"deserve; be worth; be worthy of", example:"这本小说值得读一读。"},
  {word:"职业", pinyin:"zhíyè", meaning:"occupation; profession; vocation", example:"你理想中的职业是什么？"},
  {word:"植物", pinyin:"zhíwù", meaning:"plant", example:"这种植物我们都没见过。"},
  {word:"只好", pinyin:"zhǐhǎo", meaning:"have to; be obliged to; cannot… but…", example:"雨下得太大了，我们只好留在家里。"},
  {word:"只要", pinyin:"zhǐyào", meaning:"only if; so long as", example:"只要努力，你一定能把这件事做好。"},
  {word:"只有", pinyin:"zhǐyǒu", meaning:"only", example:"只有你能解决这个问题。"},
  {word:"指", pinyin:"zhǐ", meaning:"point to", example:"他指着前面，高兴地说：“你看，小王来了。”"},
  {word:"至少", pinyin:"zhìshǎo", meaning:"at least", example:"这座楼至少有100米高。"},
  {word:"质量", pinyin:"zhìliàng", meaning:"quality", example:"这双鞋质量非常好。"},
  {word:"重", pinyin:"zhòng", meaning:"heavy", example:"桌子太重了，我帮你一起搬吧。"},
  {word:"重点", pinyin:"zhòngdiǎn", meaning:"key point", example:"他刚才说的才是问题的重点。"},
  {word:"重视", pinyin:"zhòngshì", meaning:"attach importance to; make much of", example:"我们非常重视体育锻炼。"},
  {word:"周围", pinyin:"zhōuwéi", meaning:"surrounding", example:"学校周围有一大片森林。"},
  {word:"主意", pinyin:"zhǔyi", meaning:"opinion; idea; plan", example:"你有什么好主意，说来听听。"},
  {word:"祝贺", pinyin:"zhùhè", meaning:"celebrate; congratulate", example:"祝贺你取得了这么好的成绩。"},
  {word:"著名", pinyin:"zhùmíng", meaning:"famous; celebrated", example:"他是个著名的演员。"},
  {word:"专门", pinyin:"zhuānmén", meaning:"specially; technically", example:"我是专门来看你的。"},
  {word:"专业", pinyin:"zhuānyè", meaning:"major; specialty", example:"你在大学是学什么专业的？"},
  {word:"转", pinyin:"zhuǎn", meaning:"turn", example:"前面第一个路口向左转，你就能看到医院了。"},
  {word:"赚", pinyin:"zhuàn", meaning:"make a profit; gain; earn", example:"他做生意赚了不少钱。"},
  {word:"准确", pinyin:"zhǔnquè", meaning:"exact; precise", example:"你的答案非常准确。"},
  {word:"准时", pinyin:"zhǔnshí", meaning:"on time; punctually", example:"会议准时开始了。"},
  {word:"仔细", pinyin:"zǐxì", meaning:"careful; attentive", example:"她做事十分仔细。"},
  {word:"自然", pinyin:"zìrán", meaning:"nature; natural world", example:"我们需要保护自然环境。"},
  {word:"自信", pinyin:"zìxìn", meaning:"self-confident", example:"她是个非常自信的女孩子。"},
  {word:"总结", pinyin:"zǒngjié", meaning:"summarize; sum up", example:"请为我们总结您的成功经验。"},
  {word:"租", pinyin:"zū", meaning:"rent", example:"我在公司附近租了房子。"},
  {word:"最好", pinyin:"zuìhǎo", meaning:"had better; would be best; may as well do", example:"外面下雪了，你最好多穿件衣服。"},
  {word:"最近", pinyin:"zuìjìn", meaning:"recently; of late; lately", example:"我最近很忙。"},
  {word:"尊重", pinyin:"zūnzhòng", meaning:"respect; esteem", example:"我们都很尊重您的意见。"},
  {word:"左右", pinyin:"zuǒyòu", meaning:"around; about; approximately", example:"他看起来四十岁左右。"},
  {word:"作家", pinyin:"zuòjiā", meaning:"writer; author", example:"这位作家的小说你读过吗？"},
  {word:"作者", pinyin:"zuòzhě", meaning:"author; writer", example:"这本书的作者很有名。"},
  {word:"座位", pinyin:"zuòwèi", meaning:"seat", example:"这辆汽车上有23个座位。"}
];
