// words.js – HSK 1 full vocabulary (150 words) with examples
window.HSK1_WORDS = [
  { word: "爱", pinyin: "ài", meaning: "to love; to like doing sth.", example: "妈妈，我爱你。 / 我爱吃米饭。" },
  { word: "八", pinyin: "bā", meaning: "eight", example: "他儿子今年八岁了。" },
  { word: "爸爸", pinyin: "bàba", meaning: "father; dad; daddy", example: "我爸爸是医生。" },
  { word: "杯子", pinyin: "bēizi", meaning: "cup; glass", example: "杯子里有茶。" },
  { word: "北京", pinyin: "Běijīng", meaning: "Beijing", example: "我住在北京。" },
  { word: "本", pinyin: "běn", meaning: "copy; issue; notebook", example: "桌子上有一本书。 / 请大家把作业本儿拿出来。" },
  { word: "不客气", pinyin: "bú kèqi", meaning: "You're welcome.", example: "甲：谢谢你！乙：不客气。" },
  { word: "不", pinyin: "bù", meaning: "not; no", example: "我不是学生。" },
  { word: "菜", pinyin: "cài", meaning: "vegetable; dish", example: "我去超市买点儿菜。 / 今天我做了三个菜。" },
  { word: "茶", pinyin: "chá", meaning: "tea", example: "请喝杯茶吧。" },
  { word: "吃", pinyin: "chī", meaning: "to eat", example: "请吃点儿米饭。" },
  { word: "出租车", pinyin: "chūzūchē", meaning: "taxi", example: "我们坐出租车去火车站。" },
  { word: "打电话", pinyin: "dǎ diànhuà", meaning: "make a phone call", example: "他在打电话呢。" },
  { word: "大", pinyin: "dà", meaning: "big; large; huge; great", example: "这个苹果很大。" },
  { word: "的", pinyin: "de", meaning: "of (marker of attributive); emphasizing", example: "这是我的书。 / 我是坐飞机来中国的。" },
  { word: "点", pinyin: "diǎn", meaning: "o'clock; to order; to light", example: "现在是下午3点20。 / 先生，请问您什么时候开始点菜？" },
  { word: "电脑", pinyin: "diànnǎo", meaning: "computer", example: "我买了个电脑。" },
  { word: "电视", pinyin: "diànshì", meaning: "television", example: "妈妈在看电视。" },
  { word: "电影", pinyin: "diànyǐng", meaning: "movie; film", example: "我喜欢看电影。" },
  { word: "东西", pinyin: "dōngxi", meaning: "thing; object", example: "我在商店买了很多东西。" },
  { word: "都", pinyin: "dōu", meaning: "all; already; used to emphasize", example: "我们都来了。 / 现在都三点了，我们快迟到了。" },
  { word: "读", pinyin: "dú", meaning: "to read", example: "你会读这个汉字吗？ / 你喜欢读书吗？" },
  { word: "对不起", pinyin: "duìbuqǐ", meaning: "I'm sorry.", example: "甲：对不起。乙：没关系。" },
  { word: "多", pinyin: "duō", meaning: "a lot of; how (in questions); how (exclamation)", example: "这里的人很多。 / 你儿子多大了？ / 他跑得多快啊！" },
  { word: "多少", pinyin: "duōshao", meaning: "how many; how much", example: "你们学校有多少学生？" },
  { word: "儿子", pinyin: "érzi", meaning: "son", example: "我儿子三岁了。" },
  { word: "二", pinyin: "èr", meaning: "two", example: "现在十二点了。" },
  { word: "饭店", pinyin: "fàndiàn", meaning: "restaurant; hotel", example: "中午我们去饭店吃吧。" },
  { word: "飞机", pinyin: "fēijī", meaning: "plane", example: "我坐飞机去北京。" },
  { word: "分钟", pinyin: "fēnzhōng", meaning: "minute", example: "我想休息几分钟。" },
  { word: "高兴", pinyin: "gāoxìng", meaning: "happy; glad", example: "今天我很高兴。" },
  { word: "个", pinyin: "gè", meaning: "(general measure word)", example: "我是一个学生。" },
  { word: "工作", pinyin: "gōngzuò", meaning: "job; to work", example: "我很喜欢现在的工作。 / 我在医院工作。" },
  { word: "汉语", pinyin: "Hànyǔ", meaning: "Chinese language", example: "他在学习汉语。" },
  { word: "好", pinyin: "hǎo", meaning: "good; ok; very", example: "今天天气很好。 / 你听我说，好吗？ / 你的衣服好漂亮啊！" },
  { word: "号", pinyin: "hào", meaning: "date; number", example: "今天是2002年1月1号。 / 你的房间号是多少？" },
  { word: "喝", pinyin: "hē", meaning: "to drink", example: "我想喝水。" },
  { word: "和", pinyin: "hé", meaning: "and; with", example: "爸爸和妈妈都在家。 / 他和王先生说话呢。" },
  { word: "很", pinyin: "hěn", meaning: "very", example: "李小姐很漂亮。" },
  { word: "后面", pinyin: "hòumiàn", meaning: "at the back; later", example: "商店在学校后面。 / 关于这个问题，后面我还会详细说。" },
  { word: "回", pinyin: "huí", meaning: "to go back; (measure word for times)", example: "我八点回家。 / 我去过一回北京。" },
  { word: "会", pinyin: "huì", meaning: "can; be capable of; resultative; may; meeting", example: "我会开车。 / 我学会了汉语。 / 明天是不会下雨的。 / 我们在开会。" },
  { word: "几", pinyin: "jǐ", meaning: "how many; express an indeterminate amount", example: "你有几个儿子？ / 我家里来了几个人。" },
  { word: "家", pinyin: "jiā", meaning: "home; (measure word for families)", example: "我家在北京。 / 我哥哥开了一家公司。" },
  { word: "叫", pinyin: "jiào", meaning: "to call (by name)", example: "我的名字叫李明。" },
  { word: "今天", pinyin: "jīntiān", meaning: "today; now", example: "我今天去北京。 / 在现在，过去的东西我们都不太理解了。" },
  { word: "九", pinyin: "jiǔ", meaning: "nine", example: "今天是八月九日。" },
  { word: "开", pinyin: "kāi", meaning: "to drive; to open; to hold", example: "我开了三年出租车了。 / 请开门，让我进去。 / 我们学校在每年夏天开运动会。" },
  { word: "看", pinyin: "kàn", meaning: "to look; to watch; to read", example: "你看，那本书在桌子上呢。 / 我在看书呢。" },
  { word: "看见", pinyin: "kànjiàn", meaning: "to see", example: "我没看见他。" },
  { word: "块", pinyin: "kuài", meaning: "RMB Yuan; piece; together", example: "这本书三十块钱。 / 来吃块西瓜吧。 / 我跟朋友在一块儿呢。" },
  { word: "来", pinyin: "lái", meaning: "to come; used to indicate some action", example: "他是昨天来这儿的。 / 再来点儿水果，怎么样？" },
  { word: "老师", pinyin: "lǎoshī", meaning: "teacher", example: "他就是我们的汉语老师。" },
  { word: "了", pinyin: "le", meaning: "(particle indicating change or completion)", example: "昨天下雨了。 / 我吃了饭就去你那里。" },
  { word: "冷", pinyin: "lěng", meaning: "cold", example: "今天太冷了。" },
  { word: "里", pinyin: "lǐ", meaning: "interior; inside", example: "我们都在学校里。" },
  { word: "零", pinyin: "líng", meaning: "zero", example: "今年是二零一二年。" },
  { word: "六", pinyin: "liù", meaning: "six", example: "桌子上有六个杯子。" },
  { word: "妈妈", pinyin: "māma", meaning: "mother", example: "我妈妈不在家。" },
  { word: "吗", pinyin: "ma", meaning: "(question particle)", example: "你是中国人吗？" },
  { word: "买", pinyin: "mǎi", meaning: "to buy", example: "我买了一些苹果。" },
  { word: "没关系", pinyin: "méi guānxi", meaning: "That's all right; have no relation with", example: "甲：对不起！乙：没关系。 / 这件事，跟我没关系。" },
  { word: "没有", pinyin: "méiyǒu", meaning: "have nothing; cannot compare", example: "我家里没有人。 / 我没有他高。" },
  { word: "米饭", pinyin: "mǐfàn", meaning: "cooked rice", example: "我爱吃米饭。" },
  { word: "明天", pinyin: "míngtiān", meaning: "tomorrow", example: "今天星期日，明天是星期一。" },
  { word: "名字", pinyin: "míngzi", meaning: "name", example: "我的名字叫李明。" },
  { word: "哪", pinyin: "nǎ", meaning: "which", example: "哪个杯子是你的？" },
  { word: "哪儿", pinyin: "nǎr", meaning: "where", example: "你家在哪儿？" },
  { word: "那（那儿）", pinyin: "nà (nàr)", meaning: "that; there", example: "我不认识那个人。 / 我们的车在那儿。" },
  { word: "呢", pinyin: "ne", meaning: "(question particle; statement particle)", example: "你们家有几个人呢？ / 我在睡觉呢。" },
  { word: "能", pinyin: "néng", meaning: "can; may", example: "我能坐在这儿吗？" },
  { word: "你", pinyin: "nǐ", meaning: "you", example: "你认识这个人吗？" },
  { word: "年", pinyin: "nián", meaning: "year", example: "我在中国住了三年。" },
  { word: "女儿", pinyin: "nǚ'ér", meaning: "daughter", example: "我有两个女儿。" },
  { word: "朋友", pinyin: "péngyou", meaning: "friend", example: "他是我的好朋友。" },
  { word: "漂亮", pinyin: "piàoliang", meaning: "beautiful; pretty", example: "你的衣服真漂亮。" },
  { word: "苹果", pinyin: "píngguǒ", meaning: "apple", example: "你想不想吃个苹果？" },
  { word: "七", pinyin: "qī", meaning: "seven", example: "一个星期有七天。" },
  { word: "钱", pinyin: "qián", meaning: "money", example: "一个苹果三块钱。" },
  { word: "前面", pinyin: "qiánmiàn", meaning: "before; in front", example: "前面那个人是我的同学。" },
  { word: "请", pinyin: "qǐng", meaning: "please; to request; to entertain", example: "请坐在椅子上。 / 我去请老师帮忙。 / 他想请我吃饭。" },
  { word: "去", pinyin: "qù", meaning: "to go; (direction particle); to remove", example: "我星期三去中国。 / 小猫跑到房间里去了。 / 把这个字去掉，这个句子就对了。" },
  { word: "热", pinyin: "rè", meaning: "hot; to heat up", example: "今天很热。 / 我去热一下米饭。" },
  { word: "人", pinyin: "rén", meaning: "person; people", example: "商店里有很多人。" },
  { word: "认识", pinyin: "rènshi", meaning: "to get to know", example: "认识你很高兴。" },
  { word: "三", pinyin: "sān", meaning: "three", example: "我有三本书。" },
  { word: "商店", pinyin: "shāngdiàn", meaning: "shop; store", example: "她去商店买东西了。" },
  { word: "上", pinyin: "shàng", meaning: "on; to go to (school, work); to go up", example: "水果在桌子上。 / 我们八点去上学。 / 我们坐电梯上楼。" },
  { word: "上午", pinyin: "shàngwǔ", meaning: "morning", example: "现在是上午10点。" },
  { word: "少", pinyin: "shǎo", meaning: "few; to be short of", example: "杯子里的水很少。 / 我还少本书。" },
  { word: "谁", pinyin: "shéi", meaning: "who", example: "那个人是谁？" },
  { word: "什么", pinyin: "shénme", meaning: "what", example: "你看见了什么？ / 你真棒，什么都会！" },
  { word: "十", pinyin: "shí", meaning: "ten", example: "现在是十月。" },
  { word: "时候", pinyin: "shíhou", meaning: "moment; time", example: "我回家的时候，他在睡觉。" },
  { word: "是", pinyin: "shì", meaning: "to be; yes", example: "他不是学生。 / 甲：你是中国人吗？乙：是，我是中国人。" },
  { word: "书", pinyin: "shū", meaning: "book", example: "我喜欢读书。" },
  { word: "水", pinyin: "shuǐ", meaning: "water", example: "杯子里还有水吗？" },
  { word: "水果", pinyin: "shuǐguǒ", meaning: "fruit", example: "我想去商店买水果。" },
  { word: "睡觉", pinyin: "shuìjiào", meaning: "to sleep", example: "儿子在睡觉呢。" },
  { word: "说", pinyin: "shuō", meaning: "to speak; to say", example: "你在说什么？" },
  { word: "说话", pinyin: "shuōhuà", meaning: "to speak; to talk", example: "他们在说话。" },
  { word: "四", pinyin: "sì", meaning: "four", example: "我们四个人去看电影。" },
  { word: "岁", pinyin: "suì", meaning: "year (of age)", example: "李医生今年40岁。" },
  { word: "他", pinyin: "tā", meaning: "he; him", example: "他是我们的老师。" },
  { word: "她", pinyin: "tā", meaning: "she; her", example: "我认识她的妈妈。" },
  { word: "太", pinyin: "tài", meaning: "very; too", example: "这个学校太大了。 / 这个苹果太大，我吃不完。" },
  { word: "天气", pinyin: "tiānqì", meaning: "weather", example: "今天的天气非常好。" },
  { word: "听", pinyin: "tīng", meaning: "to hear; to obey", example: "你听，谁来了？ / 这件事儿，我听你的。" },
  { word: "同学", pinyin: "tóngxué", meaning: "student; classmate", example: "同学们，你们好！" },
  { word: "喂", pinyin: "wèi", meaning: "hello; hey", example: "喂，李老师在吗？" },
  { word: "我", pinyin: "wǒ", meaning: "I; me", example: "我是一个学生。" },
  { word: "我们", pinyin: "wǒmen", meaning: "we; us", example: "我们都是学生。" },
  { word: "五", pinyin: "wǔ", meaning: "five", example: "今天是星期五。" },
  { word: "喜欢", pinyin: "xǐhuan", meaning: "to like", example: "我喜欢学汉语。" },
  { word: "下", pinyin: "xià", meaning: "under; to fall; next; to go down; to finish", example: "小猫在桌子下面。 / 今天下雨了。 / 我下个月去北京。 / 他在下飞机呢。 / 我们八点下班。" },
  { word: "下午", pinyin: "xiàwǔ", meaning: "afternoon", example: "我今天下午不去学校了。" },
  { word: "下雨", pinyin: "xià yǔ", meaning: "to rain", example: "昨天下雨了。" },
  { word: "先生", pinyin: "xiānsheng", meaning: "Mr.; sir", example: "你也认识王先生？" },
  { word: "现在", pinyin: "xiànzài", meaning: "now", example: "现在是12点。" },
  { word: "想", pinyin: "xiǎng", meaning: "to want to; to think; to miss", example: "我想星期六去北京。 / 妈妈，你在想什么呢？ / 爸爸，我想你了。" },
  { word: "小", pinyin: "xiǎo", meaning: "small; to become smaller; youngest", example: "这个苹果太小了。 / 雨小了，我们现在走吧。 / 这是我的小儿子，他还有个哥哥。" },
  { word: "小姐", pinyin: "xiǎojiě", meaning: "Miss", example: "小姐，你叫什么名字？" },
  { word: "些", pinyin: "xiē", meaning: "some; a little bit", example: "我买了些苹果。 / 我的病好些了。" },
  { word: "写", pinyin: "xiě", meaning: "to write", example: "你写的字很漂亮。" },
  { word: "谢谢", pinyin: "xièxie", meaning: "to thank", example: "甲：谢谢你。乙：不客气！" },
  { word: "星期", pinyin: "xīngqī", meaning: "week", example: "一个星期有七天。" },
  { word: "学生", pinyin: "xuésheng", meaning: "student", example: "我们学校里的学生很多。" },
  { word: "学习", pinyin: "xuéxí", meaning: "to study; to learn", example: "你喜欢学习汉语吗？" },
  { word: "学校", pinyin: "xuéxiào", meaning: "school", example: "我们学校很大。" },
  { word: "一", pinyin: "yī", meaning: "one; used between a reduplicative verb", example: "这儿一个人都没有。 / 请让我看一看。" },
  { word: "一点儿", pinyin: "yìdiǎnr", meaning: "a little", example: "我只有一点儿钱。" },
  { word: "衣服", pinyin: "yīfu", meaning: "clothing; clothes", example: "我在商店买了很多衣服。" },
  { word: "医生", pinyin: "yīshēng", meaning: "doctor", example: "他是这个医院里的医生。" },
  { word: "医院", pinyin: "yīyuàn", meaning: "hospital", example: "这是一个大医院。" },
  { word: "椅子", pinyin: "yǐzi", meaning: "chair", example: "小狗在椅子下面呢。" },
  { word: "有", pinyin: "yǒu", meaning: "to have; there be", example: "我有一个女儿。 / 桌子上有一本书。" },
  { word: "月", pinyin: "yuè", meaning: "month", example: "一年有12个月。" },
  { word: "再见", pinyin: "zàijiàn", meaning: "goodbye", example: "妈妈，我去学校了，再见。" },
  { word: "在", pinyin: "zài", meaning: "to be at; in the process of", example: "书在桌子上。 / 我在吃饭呢。" },
  { word: "怎么", pinyin: "zěnme", meaning: "how", example: "你怎么去北京？" },
  { word: "怎么样", pinyin: "zěnmeyàng", meaning: "How about it?", example: "我们去看电影，怎么样？" },
  { word: "这（这儿）", pinyin: "zhè (zhèr)", meaning: "this; here", example: "这个人是我的同学。 / 我能坐在这儿吗？" },
  { word: "中国", pinyin: "Zhōngguó", meaning: "China", example: "我在中国学汉语。" },
  { word: "中午", pinyin: "zhōngwǔ", meaning: "noon", example: "我今天中午去火车站。" },
  { word: "住", pinyin: "zhù", meaning: "to live; to stay", example: "他在北京住了很多年。" },
  { word: "桌子", pinyin: "zhuōzi", meaning: "desk; table", example: "电脑在桌子上。" },
  { word: "字", pinyin: "zì", meaning: "written Chinese character", example: "这个字你认识吗？" },
  { word: "昨天", pinyin: "zuótiān", meaning: "yesterday", example: "他昨天没去学校。" },
  { word: "坐", pinyin: "zuò", meaning: "to sit; to travel by (vehicle)", example: "他一个下午都坐在电视前。 / 我坐飞机去中国。" },
  { word: "做", pinyin: "zuò", meaning: "to make; to be; to do", example: "今天妈妈做了很多菜。 / 你是做什么工作的？ / 我每天做作业。" }
];
