// words_hsk2.js – HSK 2 vocabulary (150 words) with examples
window.HSK2_WORDS = [
  { word: "吧", pinyin: "ba", meaning: "(particle) used to express speculative interrogation or imperative", example: "你是个学生吧？ / 请你走吧！" },
  { word: "白", pinyin: "bái", meaning: "white", example: "我很爱穿那件白衣服。" },
  { word: "百", pinyin: "bǎi", meaning: "one hundred", example: "这个自行车五百多元。" },
  { word: "帮助", pinyin: "bāngzhù", meaning: "to help; assist; aid; support", example: "请帮我找一家搬家公司，好吗？" },
  { word: "报纸", pinyin: "bàozhǐ", meaning: "newspaper", example: "我每天早上都要读报纸。" },
  { word: "比", pinyin: "bǐ", meaning: "(prep) used to make comparison", example: "我的孩子比我高。" },
  { word: "别", pinyin: "bié", meaning: "don't", example: "太晚了，别看电视了。" },
  { word: "长", pinyin: "cháng", meaning: "long", example: "姐姐的腿长，跑得快。" },
  { word: "唱歌", pinyin: "chànggē", meaning: "to sing", example: "我最爱唱歌了，我给你们唱一个。" },
  { word: "出", pinyin: "chū", meaning: "to exit; to happen; (direction particle)", example: "我已经走出火车站了。 / 你帮我看看，这台电脑出什么问题了？" },
  { word: "穿", pinyin: "chuān", meaning: "to wear; put on", example: "天冷了，多穿些衣服吧。" },
  { word: "次", pinyin: "cì", meaning: "(measure word) number of times", example: "我去过一次北京。" },
  { word: "从", pinyin: "cóng", meaning: "from; since", example: "从我家到公司，开车要20分钟。" },
  { word: "错", pinyin: "cuò", meaning: "wrong; incorrect", example: "对不起，我错了。" },
  { word: "打篮球", pinyin: "dǎ lánqiú", meaning: "to play basketball", example: "我每天下午都去打篮球。" },
  { word: "大家", pinyin: "dàjiā", meaning: "everyone; everybody", example: "请大家不要等我了。" },
  { word: "到", pinyin: "dào", meaning: "to arrive; reach", example: "我早上9点到公司。" },
  { word: "得", pinyin: "de", meaning: "(complement particle)", example: "你走得太快了。" },
  { word: "等", pinyin: "děng", meaning: "to wait", example: "你还要再等我10分钟。" },
  { word: "弟弟", pinyin: "dìdi", meaning: "younger brother", example: "在我们家，我最大，我下面还有两个弟弟。" },
  { word: "第一", pinyin: "dì-yī", meaning: "first", example: "这是我第一次见到他。" },
  { word: "懂", pinyin: "dǒng", meaning: "to understand", example: "你的意思我懂了。" },
  { word: "对", pinyin: "duì", meaning: "right; correct", example: "你是对的，我错了。" },
  { word: "对", pinyin: "duì", meaning: "(prep) to; towards", example: "孩子对妈妈说：“妈妈，我爱你。”" },
  { word: "房间", pinyin: "fángjiān", meaning: "room", example: "我们两个人住一个房间。" },
  { word: "非常", pinyin: "fēicháng", meaning: "very", example: "奶奶非常喜欢我们送的礼物。" },
  { word: "服务员", pinyin: "fúwùyuán", meaning: "attendant; waiter; waitress", example: "我在饭馆做服务员。" },
  { word: "高", pinyin: "gāo", meaning: "tall; high", example: "我比爸爸还高。" },
  { word: "告诉", pinyin: "gàosu", meaning: "to tell", example: "你能告诉我学校怎么走吗？" },
  { word: "哥哥", pinyin: "gēge", meaning: "elder brother", example: "我哥哥比我大三岁。" },
  { word: "给", pinyin: "gěi", meaning: "to hand over; (prep) for", example: "请把这本书给他。 / 这是给你买的。" },
  { word: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "bus", example: "坐公共汽车去，要20分钟。" },
  { word: "公司", pinyin: "gōngsī", meaning: "company; firm", example: "我在一个公司上班。" },
  { word: "狗", pinyin: "gǒu", meaning: "dog", example: "女儿很喜欢小狗。" },
  { word: "贵", pinyin: "guì", meaning: "expensive; costly", example: "这块手表很贵。" },
  { word: "过", pinyin: "guo", meaning: "(particle) used after a verb to indicate past experience", example: "我没看过这本书。" },
  { word: "还", pinyin: "hái", meaning: "still; yet; in addition", example: "他还没来呢。 / 除了不吃肉，我还不吃鸡蛋。" },
  { word: "孩子", pinyin: "háizi", meaning: "son or daughter; child", example: "我有三个孩子。 / 我们这里女孩子比男孩子多。" },
  { word: "好吃", pinyin: "hǎochī", meaning: "delicious", example: "您做的米饭真好吃。" },
  { word: "黑", pinyin: "hēi", meaning: "black; dark", example: "我不喜欢黑颜色的衣服。" },
  { word: "红", pinyin: "hóng", meaning: "red", example: "我的自行车是红色的。" },
  { word: "欢迎", pinyin: "huānyíng", meaning: "to welcome", example: "欢迎你们来我们家。" },
  { word: "回答", pinyin: "huídá", meaning: "to answer; answer; reply", example: "我能回答这个问题。 / 你的回答不能让人满意。" },
  { word: "火车站", pinyin: "huǒchēzhàn", meaning: "railway station", example: "我下午3点去火车站。" },
  { word: "机场", pinyin: "jīchǎng", meaning: "airport", example: "我在机场工作了三年了。" },
  { word: "鸡蛋", pinyin: "jīdàn", meaning: "egg", example: "我每天早上都要吃个鸡蛋。" },
  { word: "件", pinyin: "jiàn", meaning: "(measure word) for clothes and things", example: "这件衣服颜色非常好看。" },
  { word: "教室", pinyin: "jiàoshì", meaning: "classroom", example: "请大家都到教室去上课。" },
  { word: "姐姐", pinyin: "jiějie", meaning: "elder sister", example: "我有两个姐姐。" },
  { word: "介绍", pinyin: "jièshào", meaning: "to introduce; introduction", example: "我来介绍一下我的朋友。 / 我在报纸上看到了这个电影的介绍。" },
  { word: "进", pinyin: "jìn", meaning: "to enter", example: "我马上就要进机场了。" },
  { word: "近", pinyin: "jìn", meaning: "close; near; intimate", example: "我们家离公司很近。 / 我跟小王的关系很近。" },
  { word: "就", pinyin: "jiù", meaning: "indicating certainty; immediately", example: "我就知道他会来的。 / 我一到家就给他打电话。" },
  { word: "觉得", pinyin: "juéde", meaning: "to feel; think", example: "你觉得这本书怎么样？" },
  { word: "咖啡", pinyin: "kāfēi", meaning: "coffee", example: "您想喝咖啡，还是茶？" },
  { word: "开始", pinyin: "kāishǐ", meaning: "to start; beginning", example: "我们从第十课开始学习。 / (学汉字)开始可能会觉得有点难。" },
  { word: "考试", pinyin: "kǎoshì", meaning: "examination; to take a test", example: "为了准备考试，他每天都学习到很晚。" },
  { word: "可能", pinyin: "kěnéng", meaning: "may; possible", example: "我可能不能去上班了。 / 这件事，完全是可能的。" },
  { word: "可以", pinyin: "kěyǐ", meaning: "can; may; not bad", example: "你可以开我的车去上班。 / 这个菜做得还可以。" },
  { word: "课", pinyin: "kè", meaning: "lesson; class", example: "今天我们学习第一课。 / 现在，我们上课。" },
  { word: "快", pinyin: "kuài", meaning: "fast; be going to", example: "他跑得真快。 / 7点50了，快上课了。" },
  { word: "快乐", pinyin: "kuàilè", meaning: "happy; happiness", example: "祝你生日快乐！ / 女儿给我的生活带来很多快乐。" },
  { word: "累", pinyin: "lèi", meaning: "tired; fatigued", example: "我累了，想休息。" },
  { word: "离", pinyin: "lí", meaning: "away from", example: "我家离学校很近。" },
  { word: "两", pinyin: "liǎng", meaning: "two", example: "苹果两块钱一斤。" },
  { word: "路", pinyin: "lù", meaning: "road; (measure word for bus routes)", example: "我每天走路去上学。 / 我们可以坐10路公共汽车去。" },
  { word: "旅游", pinyin: "lǚyóu", meaning: "to travel", example: "我们开车去旅游。" },
  { word: "卖", pinyin: "mài", meaning: "to sell", example: "这个商店卖的东西比较便宜。" },
  { word: "慢", pinyin: "màn", meaning: "slow", example: "我们走得很慢。" },
  { word: "忙", pinyin: "máng", meaning: "busy; to be busy doing", example: "这个星期，我很忙。 / 你在忙什么呢？" },
  { word: "猫", pinyin: "māo", meaning: "cat", example: "你的小猫去哪儿了？" },
  { word: "每", pinyin: "měi", meaning: "every; each", example: "你每天都看报纸吗？" },
  { word: "妹妹", pinyin: "mèimei", meaning: "younger sister", example: "我有两个妹妹。" },
  { word: "门", pinyin: "mén", meaning: "door; (measure word for school subjects)", example: "我在门外等你。 / 今年我有五门课。" },
  { word: "男", pinyin: "nán", meaning: "man; male", example: "我不认识那个男人。" },
  { word: "您", pinyin: "nín", meaning: "you (respectful)", example: "老师，您好！" },
  { word: "牛奶", pinyin: "niúnǎi", meaning: "milk", example: "睡觉前喝杯牛奶吧。" },
  { word: "女", pinyin: "nǚ", meaning: "woman; female", example: "那个女人你认识吗？" },
  { word: "旁边", pinyin: "pángbiān", meaning: "side; nearby", example: "爸爸在我旁边。" },
  { word: "跑步", pinyin: "pǎobù", meaning: "to run; jog", example: "我每天早上都跑步。" },
  { word: "便宜", pinyin: "piányi", meaning: "cheap; inexpensive", example: "苹果很便宜，我们买点儿吧。" },
  { word: "票", pinyin: "piào", meaning: "ticket", example: "我要去火车站买车票。" },
  { word: "妻子", pinyin: "qīzi", meaning: "wife", example: "我妻子上班去了。" },
  { word: "起床", pinyin: "qǐchuáng", meaning: "to get up", example: "我早上七点起床。" },
  { word: "千", pinyin: "qiān", meaning: "thousand", example: "这个手机一千元。" },
  { word: "铅笔", pinyin: "qiānbǐ", meaning: "pencil", example: "你看见我的铅笔了吗？" },
  { word: "晴", pinyin: "qíng", meaning: "fine; clear", example: "今天是晴天。" },
  { word: "去年", pinyin: "qùnián", meaning: "last year", example: "我是去年8月来北京的。" },
  { word: "让", pinyin: "ràng", meaning: "to let; allow; to transfer", example: "他爸爸不让他来。 / 他把座位让给了一位老人。" },
  { word: "日", pinyin: "rì", meaning: "day or date", example: "今天是2012年2月26日。" },
  { word: "上班", pinyin: "shàngbān", meaning: "to go to work; start work", example: "我七点半去上班。" },
  { word: "身体", pinyin: "shēntǐ", meaning: "body", example: "今天我的身体不太舒服。" },
  { word: "生病", pinyin: "shēngbìng", meaning: "to fall ill", example: "我生病了，不能去上班了。" },
  { word: "生日", pinyin: "shēngrì", meaning: "birthday", example: "祝你生日快乐！" },
  { word: "时间", pinyin: "shíjiān", meaning: "time", example: "我没时间去北京。" },
  { word: "事情", pinyin: "shìqing", meaning: "matter; affair", example: "你下午有什么事情吗？" },
  { word: "手表", pinyin: "shǒubiǎo", meaning: "watch", example: "这块手表非常漂亮。" },
  { word: "手机", pinyin: "shǒujī", meaning: "mobile phone", example: "你看，我新买了一个手机。" },
  { word: "送", pinyin: "sòng", meaning: "to give as a gift; to see off", example: "我送你一本书。 / 我去送一个朋友。" },
  { word: "虽然……但是……", pinyin: "suīrán…dànshì…", meaning: "though; but; however", example: "虽然下雨了，但是我们还是想去看电影。" },
  { word: "它", pinyin: "tā", meaning: "it", example: "我知道小猫在哪儿，它在桌子下面。" },
  { word: "踢足球", pinyin: "tī zúqiú", meaning: "to play soccer", example: "我和同学们在踢足球。" },
  { word: "题", pinyin: "tí", meaning: "questions; problems", example: "这个题我不会做。" },
  { word: "跳舞", pinyin: "tiàowǔ", meaning: "to dance", example: "妹妹会唱歌，也会跳舞。" },
  { word: "外", pinyin: "wài", meaning: "outer; outside; not of one's own", example: "外面下雨了。 / 那些学生是外校的。" },
  { word: "完", pinyin: "wán", meaning: "finished; used up", example: "这本书我看完了。" },
  { word: "玩", pinyin: "wán", meaning: "to play", example: "他在玩，没有学习。" },
  { word: "晚上", pinyin: "wǎnshang", meaning: "evening", example: "今天晚上我不能看电视了。" },
  { word: "为什么", pinyin: "wèi shénme", meaning: "why", example: "你为什么不喝点儿水呢？" },
  { word: "问", pinyin: "wèn", meaning: "to ask", example: "老师，我可以问你一个问题吗？" },
  { word: "问题", pinyin: "wèntí", meaning: "question; problem", example: "这个问题太难了！" },
  { word: "西瓜", pinyin: "xīguā", meaning: "watermelon", example: "请吃块儿西瓜。" },
  { word: "希望", pinyin: "xīwàng", meaning: "to hope; hope", example: "我希望你别走了。 / 孩子是爸爸、妈妈的希望。" },
  { word: "洗", pinyin: "xǐ", meaning: "to wash; to develop (photos)", example: "今天我要洗很多衣服。 / 照片要三天才能洗出来。" },
  { word: "小时", pinyin: "xiǎoshí", meaning: "hour", example: "我看了一小时的书。" },
  { word: "笑", pinyin: "xiào", meaning: "to laugh; smile", example: "听到他这么说，我们都笑了。" },
  { word: "新", pinyin: "xīn", meaning: "new", example: "这是我买的新衣服。" },
  { word: "姓", pinyin: "xìng", meaning: "surname; to take … as surname", example: "中国人的姓在名字的前面。 / 我姓张。" },
  { word: "休息", pinyin: "xiūxi", meaning: "to rest", example: "太累了，让我休息一下。" },
  { word: "雪", pinyin: "xuě", meaning: "snow", example: "今年冬天下了几次大雪。" },
  { word: "颜色", pinyin: "yánsè", meaning: "color", example: "你喜欢哪种颜色？" },
  { word: "眼睛", pinyin: "yǎnjing", meaning: "eye", example: "我的眼睛是黑色的。" },
  { word: "羊肉", pinyin: "yángròu", meaning: "mutton", example: "有些人不爱吃羊肉。" },
  { word: "药", pinyin: "yào", meaning: "medicine", example: "这个药一天吃三次。" },
  { word: "要", pinyin: "yào", meaning: "to want; to request; ought to; be going to; cost", example: "我要去北京。 / 妈妈要我去买菜。 / 你要认真地做这件事。 / 要下雨了。 / 一斤菜要两块钱。" },
  { word: "也", pinyin: "yě", meaning: "also; too", example: "你去，我也去。" },
  { word: "一下", pinyin: "yíxià", meaning: "once; in a short while", example: "请等我一下。" },
  { word: "一起", pinyin: "yìqǐ", meaning: "together", example: "我和你一起去北京。" },
  { word: "已经", pinyin: "yǐjīng", meaning: "already", example: "我们已经吃完饭了。" },
  { word: "意思", pinyin: "yìsi", meaning: "meaning; opinion; fun", example: "这个词是什么意思？ / 把你的意思告诉我吧。 / 这个电影真有有意思。" },
  { word: "因为……所以……", pinyin: "yīnwèi…suǒyǐ…", meaning: "because… therefore…", example: "因为下雨了，所以我没去跑步。" },
  { word: "阴", pinyin: "yīn", meaning: "cloudy; overcast", example: "今天是阴天。" },
  { word: "游泳", pinyin: "yóuyǒng", meaning: "to swim", example: "我会游泳了。" },
  { word: "右边", pinyin: "yòubian", meaning: "right; right side", example: "王医生右边那个人是谁？" },
  { word: "鱼", pinyin: "yú", meaning: "fish", example: "水里有很多鱼。" },
  { word: "远", pinyin: "yuǎn", meaning: "far", example: "我家离公司很远。" },
  { word: "运动", pinyin: "yùndòng", meaning: "to take exercise", example: "我们都很喜欢运动。" },
  { word: "再", pinyin: "zài", meaning: "again; more; further", example: "我吃完饭再去商店。 / 再高点儿，现在太低了。" },
  { word: "早上", pinyin: "zǎoshang", meaning: "morning", example: "我早上看见过他。" },
  { word: "丈夫", pinyin: "zhàngfu", meaning: "husband", example: "我丈夫在医院工作。" },
  { word: "找", pinyin: "zhǎo", meaning: "to look for", example: "他想找一个工作。" },
  { word: "着", pinyin: "zhe", meaning: "(particle) indicating a continuous action", example: "他笑着说：“你不认识我，但是我认识你。”" },
  { word: "真", pinyin: "zhēn", meaning: "indeed; really", example: "这个人真高。" },
  { word: "正在", pinyin: "zhèngzài", meaning: "in the process of", example: "弟弟正在打篮球。" },
  { word: "知道", pinyin: "zhīdào", meaning: "to know", example: "我不知道他现在在哪里。" },
  { word: "准备", pinyin: "zhǔnbèi", meaning: "to prepare; preparation", example: "我准备星期日去北京。 / 我在为考试做准备。" },
  { word: "自行车", pinyin: "zìxíngchē", meaning: "bicycle", example: "这是我新买的自行车。" },
  { word: "走", pinyin: "zǒu", meaning: "to walk; to leave", example: "我女儿9个月就会走了。 / 我走了，再见！" },
  { word: "最", pinyin: "zuì", meaning: "the most", example: "她是我最好的朋友。" },
  { word: "左边", pinyin: "zuǒbian", meaning: "left; left side", example: "左边的那个杯子是你的，右边的是我的。" }
];
