// words_hsk3.js – HSK 3 vocabulary (300 words) with examples
window.HSK3_WORDS = [
  { word: "阿姨", pinyin: "āyí", meaning: "aunt", example: "阿姨，附近有地铁站吗？" },
  { word: "啊", pinyin: "a", meaning: "(interjection) expressing surprise, exclamation, or promise", example: "啊，这儿的环境多么好啊！你们家住在哪儿啊？啊，好的，我现在就去。" },
  { word: "矮", pinyin: "ǎi", meaning: "short, low", example: "弟弟的个子比我矮。" },
  { word: "爱好", pinyin: "àihào", meaning: "hobby; to be fond of", example: "我最大的爱好就是打篮球。我从小就爱好音乐。" },
  { word: "安静", pinyin: "ānjìng", meaning: "quiet; to quiet down", example: "因为教室里没什么人，所以很安静。孩子们都睡着了，家里安静了下来。" },
  { word: "把", pinyin: "bǎ", meaning: "(prep) dealing with; (measure word for things with a handle)", example: "请把桌子上的铅笔给我。房间里有四把椅子。" },
  { word: "班", pinyin: "bān", meaning: "class", example: "我在三年级二班。" },
  { word: "搬", pinyin: "bān", meaning: "to carry; to move", example: "请帮我把这张桌子搬到楼下好吗？" },
  { word: "办法", pinyin: "bànfǎ", meaning: "way; method", example: "你别急，我们再想想办法。" },
  { word: "办公室", pinyin: "bàngōngshì", meaning: "office", example: "请问，校长办公室怎么走？" },
  { word: "半", pinyin: "bàn", meaning: "half", example: "现在是三点半。" },
  { word: "帮忙", pinyin: "bāngmáng", meaning: "to help", example: "因为有你帮忙，这件事情处理得很好。" },
  { word: "包", pinyin: "bāo", meaning: "bag", example: "我的包忘在房间里了。" },
  { word: "饱", pinyin: "bǎo", meaning: "full (after eating)", example: "我已经吃饱了。" },
  { word: "北方", pinyin: "běifāng", meaning: "north", example: "冬天，北方比南方冷多了。" },
  { word: "被", pinyin: "bèi", meaning: "(passive marker)", example: "词典被王老师拿走了。" },
  { word: "鼻子", pinyin: "bízi", meaning: "nose", example: "姐姐的鼻子很高，很漂亮。" },
  { word: "比较", pinyin: "bǐjiào", meaning: "fairly; quite", example: "今天天气比较冷。" },
  { word: "比赛", pinyin: "bǐsài", meaning: "competition; to compete", example: "今天晚上有足球比赛。我们比赛跑步吧。" },
  { word: "笔记本", pinyin: "bǐjìběn", meaning: "notebook; laptop", example: "老师讲的内容，我都写在笔记本上了。你看，这是我新买的笔记本。" },
  { word: "必须", pinyin: "bìxū", meaning: "must; have to", example: "我今天必须去上班。" },
  { word: "变化", pinyin: "biànhuà", meaning: "change; to change", example: "十年不见，他好像没什么变化。城市变化得太快了。" },
  { word: "别人", pinyin: "biéren", meaning: "other people", example: "别人都走了，为什么你还在这里？" },
  { word: "宾馆", pinyin: "bīnguǎn", meaning: "hotel", example: "这是我们这儿最大的宾馆，可以住300个客人。" },
  { word: "冰箱", pinyin: "bīngxiāng", meaning: "refrigerator", example: "妈妈把刚买的鱼放进了冰箱。" },
  { word: "不但……而且……", pinyin: "búdàn…érqiě…", meaning: "not only… but also…", example: "妹妹不但喜欢唱歌，而且爱跳舞。" },
  { word: "才", pinyin: "cái", meaning: "late; just; only", example: "他30岁才读完大学。这件事，只有他才能做好。" },
  { word: "菜单", pinyin: "càidān", meaning: "menu", example: "服务员，请帮我拿一下菜单。" },
  { word: "参加", pinyin: "cānjiā", meaning: "to join; to take part in", example: "这次会议有两百多人参加。" },
  { word: "草", pinyin: "cǎo", meaning: "grass", example: "春天来了，小草绿了。" },
  { word: "层", pinyin: "céng", meaning: "(measure word for layers, floors)", example: "我住在三层，306。" },
  { word: "差", pinyin: "chà", meaning: "bad; to fall short of", example: "我这次考试考得很差。现在是差5分12点。" },
  { word: "长", pinyin: "cháng", meaning: "long", example: "姐姐的头发又黑又长。" },
  { word: "超市", pinyin: "chāoshì", meaning: "supermarket", example: "这家超市里的东西比较便宜。" },
  { word: "衬衫", pinyin: "chènshān", meaning: "shirt", example: "今天我穿这件衬衫。" },
  { word: "成绩", pinyin: "chéngjì", meaning: "score", example: "我们可以在网上查到考试成绩。" },
  { word: "城市", pinyin: "chéngshì", meaning: "city", example: "我已经喜欢上了这个城市。" },
  { word: "迟到", pinyin: "chídào", meaning: "to be late", example: "对不起，我今天又迟到了。" },
  { word: "出现", pinyin: "chūxiàn", meaning: "to appear; to happen", example: "我们等了他一个小时，他也没有出现。我们工作中出现了不少问题。" },
  { word: "除了", pinyin: "chúle", meaning: "except; besides", example: "除了小王，其他人都来了。" },
  { word: "船", pinyin: "chuán", meaning: "boat; ship", example: "你可以坐船去上海。" },
  { word: "春", pinyin: "chūn", meaning: "spring", example: "春天是一年的开始。" },
  { word: "词典", pinyin: "cídiǎn", meaning: "dictionary", example: "这本词典对我的学习很有帮助。" },
  { word: "聪明", pinyin: "cōngming", meaning: "bright; clever", example: "弟弟不但很聪明，而且很爱学习。" },
  { word: "打扫", pinyin: "dǎsǎo", meaning: "to clean", example: "我准备周末把房间打扫一下。" },
  { word: "打算", pinyin: "dǎsuàn", meaning: "to plan; plan", example: "我打算下个星期去旅游。我还没有结婚的打算。" },
  { word: "带", pinyin: "dài", meaning: "to carry; to bring", example: "我今天忘记带钱包了。" },
  { word: "担心", pinyin: "dānxīn", meaning: "to worry", example: "爷爷住院了，我很担心。" },
  { word: "蛋糕", pinyin: "dàngāo", meaning: "cake", example: "你饿了吗？先吃块蛋糕吧。" },
  { word: "当然", pinyin: "dāngrán", meaning: "of course", example: "你生病了，我当然要来看看你。" },
  { word: "灯", pinyin: "dēng", meaning: "lamp", example: "房间里的灯怎么不亮了？" },
  { word: "地", pinyin: "de", meaning: "(adverbial marker)", example: "天慢慢地黑了。" },
  { word: "地方", pinyin: "dìfang", meaning: "place", example: "这个地方我来过三次了。" },
  { word: "地铁", pinyin: "dìtiě", meaning: "subway", example: "我们先坐三站地铁，再走一会儿就到了。" },
  { word: "地图", pinyin: "dìtú", meaning: "map", example: "我的手机上有电子地图。" },
  { word: "电梯", pinyin: "diàntī", meaning: "elevator", example: "我们坐电梯上去吧。" },
  { word: "电子邮件", pinyin: "diànzǐyóujiàn", meaning: "email", example: "我晚上再给你发个电子邮件。" },
  { word: "东", pinyin: "dōng", meaning: "east", example: "你一直向东走就到了。" },
  { word: "冬", pinyin: "dōng", meaning: "winter", example: "北方的冬天很冷。" },
  { word: "动物园", pinyin: "dòngwùyuán", meaning: "zoo", example: "动物园里有一百多种动物。" },
  { word: "短", pinyin: "duǎn", meaning: "short", example: "这件事在短时间内很难做完。" },
  { word: "段", pinyin: "duàn", meaning: "(measure word for paragraph, period, section)", example: "这段时间我很忙。" },
  { word: "锻炼", pinyin: "duànliàn", meaning: "to exercise", example: "我每天早上都去锻炼身体。" },
  { word: "多么", pinyin: "duōme", meaning: "how (exclamatory)", example: "这里多么漂亮啊！" },
  { word: "饿", pinyin: "è", meaning: "hungry", example: "我饿了，想吃点东西。" },
  { word: "耳朵", pinyin: "ěrduo", meaning: "ear", example: "我的耳朵有点疼，要去医院看看。" },
  { word: "发", pinyin: "fā", meaning: "to send", example: "你给我发电子邮件了吗？" },
  { word: "发烧", pinyin: "fāshāo", meaning: "to have a fever", example: "我身体不舒服，发烧了。" },
  { word: "发现", pinyin: "fāxiàn", meaning: "to discover", example: "我发现他瘦了很多。" },
  { word: "方便", pinyin: "fāngbiàn", meaning: "convenient", example: "我坐地铁去上班很方便。" },
  { word: "放", pinyin: "fàng", meaning: "to put", example: "把书放在桌子上吧。" },
  { word: "放心", pinyin: "fàngxīn", meaning: "to be assured", example: "请放心，我会把事情办好的。" },
  { word: "分", pinyin: "fēn", meaning: "minute; mark; to split", example: "现在8点30分。这次考试，我得了85分。这个苹果被分成了两块儿。" },
  { word: "附近", pinyin: "fùjìn", meaning: "nearby", example: "他家就住在公司附近。" },
  { word: "复习", pinyin: "fùxí", meaning: "to review", example: "考试前要好好地复习。" },
  { word: "干净", pinyin: "gānjìng", meaning: "clean", example: "我把衣服洗干净了。" },
  { word: "感冒", pinyin: "gǎnmào", meaning: "to catch a cold", example: "我感冒了，要吃点儿药。" },
  { word: "感兴趣", pinyin: "gǎnxìngqù", meaning: "to be interested", example: "小王对音乐很感兴趣。" },
  { word: "刚才", pinyin: "gāngcái", meaning: "a moment ago", example: "刚才是谁来的电话？" },
  { word: "个子", pinyin: "gèzi", meaning: "height", example: "哥哥比我个子高。" },
  { word: "根据", pinyin: "gēnjù", meaning: "according to; basis", example: "请根据这篇文章谈一谈自己的想法。他这么说，是有根据的。" },
  { word: "跟", pinyin: "gēn", meaning: "to follow; with", example: "散步的时候，小狗一直跟在我身后。姐姐跟妈妈一起去公园了。" },
  { word: "更", pinyin: "gèng", meaning: "more", example: "他比我更喜欢游泳。" },
  { word: "公斤", pinyin: "gōngjīn", meaning: "kilogram", example: "我买了一公斤鸡蛋。" },
  { word: "公园", pinyin: "gōngyuán", meaning: "park", example: "我家附近有个公园，我常去那里散步。" },
  { word: "故事", pinyin: "gùshi", meaning: "story", example: "睡觉前，我都给女儿讲故事。" },
  { word: "刮风", pinyin: "guāfēng", meaning: "to blow (wind)", example: "今天刮风了，别骑自行车了。" },
  { word: "关", pinyin: "guān", meaning: "to close; to turn off", example: "他关上了门。我把电视关了。" },
  { word: "关系", pinyin: "guānxì", meaning: "relation", example: "这件事和她没有关系。" },
  { word: "关心", pinyin: "guānxīn", meaning: "to care for; concern", example: "爸爸很关心我的学习。谢谢你的关心，我的身体好多了。" },
  { word: "关于", pinyin: "guānyú", meaning: "regarding", example: "关于这个问题，我们还要再想一想。" },
  { word: "国家", pinyin: "guójiā", meaning: "country", example: "我爱旅游，去过几十个国家。" },
  { word: "过", pinyin: "guò", meaning: "to pass; to spend (time)", example: "今天我过生日，朋友们都来了。时间过得真快，要过春节了。" },
  { word: "过去", pinyin: "guòqù", meaning: "in the past", example: "奶奶经常给我讲过去的事情。" },
  { word: "还是", pinyin: "háishì", meaning: "still; had better; or", example: "我还是在北京，没去其他地方。你还是吃点儿水果吧，别喝啤酒了。你是开车去还是坐公共汽车去？" },
  { word: "害怕", pinyin: "hàipà", meaning: "to be afraid", example: "我怕一个人晚上出门。" },
  { word: "航班", pinyin: "hángbān", meaning: "flight", example: "各位顾客，欢迎您乘坐我们的航班。" },
  { word: "黑板", pinyin: "hēibǎn", meaning: "blackboard", example: "请大家看黑板。" },
  { word: "后来", pinyin: "hòulái", meaning: "later", example: "后来我再也没见过他。" },
  { word: "护照", pinyin: "hùzhào", meaning: "passport", example: "你的护照办好了吗？" },
  { word: "花", pinyin: "huā", meaning: "to spend; flower", example: "今天我花了不少钱。今天是妈妈的生日，我们送一些花给她吧。" },
  { word: "画", pinyin: "huà", meaning: "to draw; picture", example: "我从小就喜欢画画儿。他的画儿很受大家欢迎。" },
  { word: "坏", pinyin: "huài", meaning: "bad; terrible", example: "面包很新鲜，没有坏。坏了，我忘记带护照了。" },
  { word: "还", pinyin: "huán", meaning: "to return", example: "我把书还给图书馆了。" },
  { word: "环境", pinyin: "huánjìng", meaning: "environment", example: "这里的环境很不错，在这里住很舒服。" },
  { word: "换", pinyin: "huàn", meaning: "to change; to exchange money", example: "你等我一下，我去换件衣服。我去银行换点儿钱。" },
  { word: "黄河", pinyin: "Huánghé", meaning: "the Yellow River", example: "黄河是中国的第二大河。" },
  { word: "会议", pinyin: "huìyì", meaning: "meeting", example: "我们下午有个会议。" },
  { word: "或者", pinyin: "huòzhě", meaning: "or", example: "你去，或者我去，都可以。" },
  { word: "几乎", pinyin: "jīhū", meaning: "nearly", example: "我感动得几乎要流泪了。" },
  { word: "机会", pinyin: "jīhuì", meaning: "opportunity", example: "我希望有机会参加比赛。" },
  { word: "极", pinyin: "jí", meaning: "extremely", example: "他对音乐极感兴趣。今天的节目好看极了。" },
  { word: "记得", pinyin: "jìde", meaning: "to remember", example: "我不记得他住在哪儿了。" },
  { word: "季节", pinyin: "jìjié", meaning: "season", example: "一年有四个季节。" },
  { word: "检查", pinyin: "jiǎnchá", meaning: "to inspect; to check", example: "你去医院检查一下身体吧。" },
  { word: "简单", pinyin: "jiǎndān", meaning: "easy", example: "这些题对他来说很简单。" },
  { word: "见面", pinyin: "jiànmiàn", meaning: "to meet", example: "上次和他见面，已经是去年了。" },
  { word: "健康", pinyin: "jiànkāng", meaning: "healthy", example: "爸爸的身体特别健康。" },
  { word: "讲", pinyin: "jiǎng", meaning: "to speak; to tell", example: "李老师的课讲得很有趣。" },
  { word: "降落", pinyin: "jiàngluò", meaning: "to land", example: "飞机马上就要降落了。" },
  { word: "角", pinyin: "jiǎo", meaning: "tenth of a yuan; corner", example: "桌上有五角钱。房间的一角放了很多书。" },
  { word: "脚", pinyin: "jiǎo", meaning: "foot", example: "妹妹脚上穿着漂亮的红皮鞋。" },
  { word: "教", pinyin: "jiāo", meaning: "to teach", example: "李老师教我们数学。" },
  { word: "接", pinyin: "jiē", meaning: "to accept; to go on", example: "下午我去机场接你。他看了看表，躺下接着睡觉。" },
  { word: "街道", pinyin: "jiēdào", meaning: "street", example: "这条街道很长，有四千多米。" },
  { word: "节目", pinyin: "jiémù", meaning: "show; program", example: "今天我们一共演出12个节目。" },
  { word: "节日", pinyin: "jiérì", meaning: "holiday", example: "祝大家节日快乐！" },
  { word: "结婚", pinyin: "jiéhūn", meaning: "to get married", example: "我们结婚10年了。" },
  { word: "结束", pinyin: "jiéshù", meaning: "to end", example: "会议马上就要结束了。" },
  { word: "解决", pinyin: "jiějué", meaning: "to solve", example: "这个问题你打算怎么解决？" },
  { word: "借", pinyin: "jiè", meaning: "to borrow; to lend", example: "我从图书馆借了三本书。" },
  { word: "经常", pinyin: "jīngcháng", meaning: "often", example: "我经常在学校遇到他。" },
  { word: "经过", pinyin: "jīngguò", meaning: "to pass through; through", example: "上下班的时候，我都要经过这条街道。经过你这么一说，我终于明白了。" },
  { word: "经理", pinyin: "jīnglǐ", meaning: "manager", example: "他是我们公司的经理。" },
  { word: "久", pinyin: "jiǔ", meaning: "long (time)", example: "这个问题我想了很久才明白。" },
  { word: "旧", pinyin: "jiù", meaning: "old", example: "这件衣服穿了两年，已经旧了。" },
  { word: "句子", pinyin: "jùzi", meaning: "sentence", example: "请用这些词语说几个句子。" },
  { word: "决定", pinyin: "juédìng", meaning: "to decide; decision", example: "这件事是经理决定的。他已经做出了决定。" },
  { word: "可爱", pinyin: "kě'ài", meaning: "cute", example: "你的儿子真可爱。" },
  { word: "渴", pinyin: "kě", meaning: "thirsty", example: "我渴了，想喝点儿水。" },
  { word: "刻", pinyin: "kè", meaning: "quarter (of an hour)", example: "现在是三点一刻。" },
  { word: "客人", pinyin: "kèrén", meaning: "guest", example: "春节的时候，家里会来很多客人。" },
  { word: "空调", pinyin: "kōngtiáo", meaning: "air conditioner", example: "太热了，请把空调打开。" },
  { word: "口", pinyin: "kǒu", meaning: "(measure word for people); mouth", example: "我们家一共三口人。想学好外语，要多开口说。" },
  { word: "哭", pinyin: "kū", meaning: "to cry", example: "孩子又哭了起来。" },
  { word: "裤子", pinyin: "kùzi", meaning: "trousers", example: "这条裤子有点儿短。" },
  { word: "筷子", pinyin: "kuàizi", meaning: "chopsticks", example: "我来中国1个月了，已经会用筷子了。" },
  { word: "蓝", pinyin: "lán", meaning: "blue", example: "这条蓝裙子你喜欢吗？" },
  { word: "老", pinyin: "lǎo", meaning: "old", example: "爷爷六十岁了，但是看起来一点儿也不老。" },
  { word: "离开", pinyin: "líkāi", meaning: "to leave", example: "下个月我要离开一段时间，你好好照顾自己。" },
  { word: "礼物", pinyin: "lǐwù", meaning: "gift", example: "过生日的时候，我收到了很多礼物。" },
  { word: "历史", pinyin: "lìshǐ", meaning: "history", example: "这个房子差不多有300年的历史了。" },
  { word: "脸", pinyin: "liǎn", meaning: "face", example: "女儿的脸圆圆的，很可爱。" },
  { word: "练习", pinyin: "liànxí", meaning: "to practice; exercise", example: "学过的东西，要多练习才能记住。同学们，下面我们开始做练习。" },
  { word: "辆", pinyin: "liàng", meaning: "(measure word for vehicles)", example: "这辆车，是我新买的。" },
  { word: "聊天", pinyin: "liáotiān", meaning: "to chat", example: "我们经常在网上聊天。" },
  { word: "了解", pinyin: "liǎojiě", meaning: "to understand", example: "我对她了解得不多。" },
  { word: "邻居", pinyin: "línjū", meaning: "neighbor", example: "我跟邻居们的关系非常好。" },
  { word: "留学", pinyin: "liúxué", meaning: "to study abroad", example: "我哥哥在中国留学。" },
  { word: "楼", pinyin: "lóu", meaning: "building", example: "我在你家楼下等你。" },
  { word: "绿", pinyin: "lǜ", meaning: "green", example: "春天来了，树和草都绿了。" },
  { word: "马", pinyin: "mǎ", meaning: "horse", example: "我们学会骑马了。" },
  { word: "马上", pinyin: "mǎshàng", meaning: "immediately", example: "我马上就到学校，你再等我几分钟。" },
  { word: "满意", pinyin: "mǎnyì", meaning: "to be satisfied", example: "经理对他很满意。" },
  { word: "帽子", pinyin: "màozi", meaning: "hat", example: "这个帽子太小了，有大一点儿的吗？" },
  { word: "米", pinyin: "mǐ", meaning: "meter", example: "这张桌子有两米长。" },
  { word: "面包", pinyin: "miànbāo", meaning: "bread", example: "面包已经卖完了。" },
  { word: "面条", pinyin: "miàntiáo", meaning: "noodle", example: "服务员，我要一碗面条。" },
  { word: "明白", pinyin: "míngbai", meaning: "to understand; clear", example: "我明白你的意思了。他说得很明白，我懂了。" },
  { word: "拿", pinyin: "ná", meaning: "to hold; to take", example: "你手里拿的是什么？" },
  { word: "奶奶", pinyin: "nǎinai", meaning: "grandmother", example: "我奶奶住在北京。" },
  { word: "南", pinyin: "nán", meaning: "south", example: "我家在火车站的南边。" },
  { word: "难", pinyin: "nán", meaning: "difficult", example: "这个题很难。" },
  { word: "难过", pinyin: "nánguò", meaning: "to have a hard time", example: "他要离开了，我很难过。" },
  { word: "年级", pinyin: "niánjí", meaning: "grade", example: "我儿子现在上三年级。" },
  { word: "年轻", pinyin: "niánqīng", meaning: "young", example: "妈妈50岁了，看起来还很年轻。" },
  { word: "鸟", pinyin: "niǎo", meaning: "bird", example: "树上有很多鸟在唱歌。" },
  { word: "努力", pinyin: "nǔlì", meaning: "hard-working", example: "学生们学习很努力。" },
  { word: "爬山", pinyin: "páshān", meaning: "to climb a mountain", example: "我们决定明天去爬山。" },
  { word: "盘子", pinyin: "pánzi", meaning: "plate", example: "盘子里有鱼，请吃吧。" },
  { word: "胖", pinyin: "pàng", meaning: "fat; to get fat", example: "熊猫很胖，很可爱。这个月我胖了五斤多。" },
  { word: "皮鞋", pinyin: "píxié", meaning: "leather shoes", example: "他穿着一双黑色的皮鞋。" },
  { word: "啤酒", pinyin: "píjiǔ", meaning: "beer", example: "爸爸爱喝啤酒。" },
  { word: "普通话", pinyin: "pǔtōnghuà", meaning: "Mandarin", example: "你的普通话说得很好。" },
  { word: "其实", pinyin: "qíshí", meaning: "actually", example: "我其实不太了解他。" },
  { word: "其他", pinyin: "qítā", meaning: "other", example: "只有小明在教室里，其他人都回家了。" },
  { word: "奇怪", pinyin: "qíguài", meaning: "strange", example: "我觉得这个问题很奇怪。" },
  { word: "骑", pinyin: "qí", meaning: "to ride", example: "今天我骑自行车去学校。" },
  { word: "起飞", pinyin: "qǐfēi", meaning: "to take off", example: "各位乘客，飞机马上就要起飞了。" },
  { word: "清楚", pinyin: "qīngchu", meaning: "clear; to understand", example: "他把这件事儿说得很清楚了。你清楚这句话的意思吗？" },
  { word: "秋", pinyin: "qiū", meaning: "autumn", example: "秋天最舒服，不冷也不热。" },
  { word: "裙子", pinyin: "qúnzi", meaning: "skirt", example: "姐姐穿着漂亮的裙子。" },
  { word: "然后", pinyin: "ránhòu", meaning: "then", example: "我要先写完作业，然后再看电视。" },
  { word: "热情", pinyin: "rèqíng", meaning: "warm", example: "我们热情地欢迎客人。" },
  { word: "认为", pinyin: "rènwéi", meaning: "to think", example: "你认为他会来吗？" },
  { word: "认真", pinyin: "rènzhēn", meaning: "serious", example: "这个同学学习很认真，很努力。" },
  { word: "容易", pinyin: "róngyì", meaning: "easy", example: "这个问题很容易回答。" },
  { word: "如果", pinyin: "rúguǒ", meaning: "if", example: "如果你去，我就和你一起去。" },
  { word: "伞", pinyin: "sǎn", meaning: "umbrella", example: "下雨了，别忘了带伞。" },
  { word: "上网", pinyin: "shàngwǎng", meaning: "to go online", example: "我上网去看看新闻。" },
  { word: "生气", pinyin: "shēngqì", meaning: "to be angry", example: "请别生气，是我错了，对不起。" },
  { word: "声音", pinyin: "shēngyīn", meaning: "sound; voice", example: "你听，这是什么声音？" },
  { word: "世界", pinyin: "shìjiè", meaning: "world", example: "世界上有很多国家。" },
  { word: "试", pinyin: "shì", meaning: "to try", example: "我想试一下那件红色的。" },
  { word: "瘦", pinyin: "shòu", meaning: "thin; to become thin", example: "姐姐现在很瘦，只有45公斤。这个月我瘦了三斤。" },
  { word: "叔叔", pinyin: "shūshu", meaning: "uncle", example: "叔叔，你喜欢这本书吗？" },
  { word: "舒服", pinyin: "shūfu", meaning: "comfortable", example: "坐在这里，真舒服。" },
  { word: "树", pinyin: "shù", meaning: "tree", example: "我们学校里有很多树。" },
  { word: "数学", pinyin: "shùxué", meaning: "mathematics", example: "我的数学成绩很好。" },
  { word: "刷牙", pinyin: "shuāyá", meaning: "to brush teeth", example: "睡觉前要刷牙。" },
  { word: "双", pinyin: "shuāng", meaning: "(measure word for pair)", example: "我今天想去买双鞋。" },
  { word: "水平", pinyin: "shuǐpíng", meaning: "level", example: "他的汉语水平很高。" },
  { word: "司机", pinyin: "sījī", meaning: "driver", example: "这位司机开出租车5年多了。" },
  { word: "太阳", pinyin: "tàiyáng", meaning: "sun", example: "你看，太阳出来了。" },
  { word: "特别", pinyin: "tèbié", meaning: "very; special", example: "我特别想跟你一起去。这个菜的做法很特别。" },
  { word: "疼", pinyin: "téng", meaning: "to ache", example: "我的腿有点儿疼。" },
  { word: "提高", pinyin: "tígāo", meaning: "to improve; improvement", example: "你数学成绩提高了不少。人们的生活水平有了很大的提高。" },
  { word: "体育", pinyin: "tǐyù", meaning: "sports", example: "我很喜欢体育运动。" },
  { word: "甜", pinyin: "tián", meaning: "sweet", example: "这个西瓜真甜啊！" },
  { word: "条", pinyin: "tiáo", meaning: "(measure word for long things)", example: "这条裤子有点儿长。" },
  { word: "同事", pinyin: "tóngshì", meaning: "colleague", example: "这是我们的新同事，李华。" },
  { word: "同意", pinyin: "tóngyì", meaning: "to agree", example: "我不太同意他的想法。" },
  { word: "头发", pinyin: "tóufa", meaning: "hair", example: "妈妈的头发又黑又亮。" },
  { word: "突然", pinyin: "tūrán", meaning: "sudden; suddenly", example: "他突然站了起来。小狗突然跑了出来。" },
  { word: "图书馆", pinyin: "túshūguǎn", meaning: "library", example: "我从图书馆借来了两本书。" },
  { word: "腿", pinyin: "tuǐ", meaning: "leg", example: "你的腿还疼吗？" },
  { word: "完成", pinyin: "wánchéng", meaning: "to complete", example: "这件事，在周末前必须完成。" },
  { word: "碗", pinyin: "wǎn", meaning: "bowl; a bowl of", example: "把米饭放在这个碗里吧。我吃一碗就可以了。" },
  { word: "万", pinyin: "wàn", meaning: "ten thousand", example: "我们学校有一万名学生。" },
  { word: "忘记", pinyin: "wàngjì", meaning: "to forget", example: "我忘记今天是他的生日了。" },
  { word: "为", pinyin: "wèi", meaning: "for", example: "这些菜都是为你准备的。" },
  { word: "为了", pinyin: "wèile", meaning: "for", example: "为了身体健康，我每天都去运动。" },
  { word: "位", pinyin: "wèi", meaning: "(measure word for people)", example: "他真是一位好老师。" },
  { word: "文化", pinyin: "wénhuà", meaning: "culture", example: "我对中国文化很感兴趣。" },
  { word: "西", pinyin: "xī", meaning: "west", example: "火车站在西边，你走错了。" },
  { word: "习惯", pinyin: "xíguàn", meaning: "to be used to; habit", example: "他已经习惯了一个人生活。饭前洗手是好习惯。" },
  { word: "洗手间", pinyin: "xǐshǒujiān", meaning: "toilet", example: "我去一下洗手间。" },
  { word: "洗澡", pinyin: "xǐzǎo", meaning: "to take a bath", example: "太热了，我先去洗澡。" },
  { word: "夏", pinyin: "xià", meaning: "summer", example: "今年夏天太热了。" },
  { word: "先", pinyin: "xiān", meaning: "first", example: "你先去，我一个小时后再去。" },
  { word: "相信", pinyin: "xiāngxìn", meaning: "to believe", example: "我完全相信你说的话。" },
  { word: "香蕉", pinyin: "xiāngjiāo", meaning: "banana", example: "你想吃香蕉吗？" },
  { word: "向", pinyin: "xiàng", meaning: "towards", example: "向东走，就可以看到那个学校了。" },
  { word: "像", pinyin: "xiàng", meaning: "to look like; for example", example: "他长得像他爸爸。像校长这样的人，到哪里都很受欢迎。" },
  { word: "小心", pinyin: "xiǎoxīn", meaning: "to be careful", example: "请小心，路上有很多水。我很小心地抱起了小猫。" },
  { word: "校长", pinyin: "xiàozhǎng", meaning: "principal; president", example: "校长已经同意了我们的计划。" },
  { word: "新闻", pinyin: "xīnwén", meaning: "news", example: "我每天晚上七点都看新闻。" },
  { word: "新鲜", pinyin: "xīnxiān", meaning: "fresh", example: "这些都是新鲜水果。" },
  { word: "信用卡", pinyin: "xìnyòngkǎ", meaning: "credit card", example: "我想去银行办一张信用卡。" },
  { word: "行李箱", pinyin: "xínglixiāng", meaning: "luggage", example: "请把行李箱打开。" },
  { word: "熊猫", pinyin: "xióngmāo", meaning: "panda", example: "我特别喜欢到动物园去看大熊猫。" },
  { word: "需要", pinyin: "xūyào", meaning: "to need", example: "我们需要一些帮助。" },
  { word: "选择", pinyin: "xuǎnzé", meaning: "to choose; choice", example: "今年夏天你选择去哪儿旅游？我们需要自己做出选择。" },
  { word: "要求", pinyin: "yāoqiú", meaning: "to demand; request", example: "老师要求我们把这些题做完。这是爸爸对我的要求。" },
  { word: "爷爷", pinyin: "yéye", meaning: "grandfather", example: "爷爷，请您坐这儿吧。" },
  { word: "一定", pinyin: "yídìng", meaning: "surely; certain", example: "明天的会议，请大家一定要参加。他的汉语已经有了一定水平。" },
  { word: "一共", pinyin: "yígòng", meaning: "altogether", example: "我们班一共有20名学生。" },
  { word: "一会儿", pinyin: "yíhuìr", meaning: "a moment", example: "我看一会儿电视就睡觉。" },
  { word: "一样", pinyin: "yíyàng", meaning: "the same", example: "他跟爸爸长得一样。" },
  { word: "一般", pinyin: "yìbān", meaning: "usually", example: "我一般7点钟起床。" },
  { word: "一边", pinyin: "yìbiān", meaning: "while", example: "他喜欢一边看书，一边听音乐。" },
  { word: "一直", pinyin: "yìzhí", meaning: "all the time", example: "我一直不明白这句话的意思。" },
  { word: "以前", pinyin: "yǐqián", meaning: "before", example: "我们看电影以前，先去吃个饭吧。" },
  { word: "音乐", pinyin: "yīnyuè", meaning: "music", example: "她最喜欢看音乐节目。" },
  { word: "银行", pinyin: "yínháng", meaning: "bank", example: "银行下午5点关门。" },
  { word: "饮料", pinyin: "yǐnliào", meaning: "beverage", example: "冰箱里还有饮料吗？" },
  { word: "应该", pinyin: "yīnggāi", meaning: "should", example: "8点了，应该去上班了。" },
  { word: "影响", pinyin: "yǐngxiǎng", meaning: "to affect; influence", example: "请不要影响别人休息。环境对人有很大的影响。" },
  { word: "用", pinyin: "yòng", meaning: "to use", example: "我用了两个小时打扫房间。" },
  { word: "游戏", pinyin: "yóuxì", meaning: "game", example: "这是孩子们最喜欢玩的游戏。" },
  { word: "有名", pinyin: "yǒumíng", meaning: "famous", example: "这本书很有名。" },
  { word: "又", pinyin: "yòu", meaning: "again", example: "我们休息了一会儿，又开始工作了。" },
  { word: "遇到", pinyin: "yùdào", meaning: "to meet", example: "刚才我在街上遇到了张先生。" },
  { word: "元", pinyin: "yuán", meaning: "RMB Yuan", example: "这块手表600元。" },
  { word: "愿意", pinyin: "yuànyì", meaning: "to be willing", example: "他很愿意帮助别人。" },
  { word: "月亮", pinyin: "yuèliang", meaning: "moon", example: "今晚的月亮真圆！" },
  { word: "越", pinyin: "yuè", meaning: "the more… the more…", example: "他越说越高兴。" },
  { word: "站", pinyin: "zhàn", meaning: "to stand; (measure for bus stops)", example: "爸爸站在我的身边。去火车站，坐地铁3站就到了。" },
  { word: "张", pinyin: "zhāng", meaning: "(measure for paper, bed, etc.); to open", example: "请给我一张纸。小女孩儿张开嘴，笑了。" },
  { word: "照顾", pinyin: "zhàogù", meaning: "to look after; care", example: "我生病了，妈妈一直照顾我。这些年，他给了我们很多照顾。" },
  { word: "照片", pinyin: "zhàopiàn", meaning: "photo", example: "这是我小时候的照片。" },
  { word: "照相机", pinyin: "zhàoxiàngjī", meaning: "camera", example: "我新买了一个照相机。" },
  { word: "只", pinyin: "zhī", meaning: "(measure word for animals, one of a pair)", example: "我有一只鞋找不到了。树上有一只小猫。" },
  { word: "只", pinyin: "zhǐ", meaning: "only", example: "房间里只有我一个人。" },
  { word: "中间", pinyin: "zhōngjiān", meaning: "center", example: "我站在中间，旁边的是我的同学。" },
  { word: "中文", pinyin: "Zhōngwén", meaning: "Chinese language", example: "我会用中文写文章。" },
  { word: "终于", pinyin: "zhōngyú", meaning: "finally", example: "春天终于来了。" },
  { word: "种", pinyin: "zhǒng", meaning: "(measure word for kind)", example: "超市里有很多种新鲜水果。" },
  { word: "重要", pinyin: "zhòngyào", meaning: "important", example: "我忘了一件重要的事情。" },
  { word: "周末", pinyin: "zhōumò", meaning: "weekend", example: "这个周末你有什么安排？" },
  { word: "主要", pinyin: "zhǔyào", meaning: "main", example: "这本书主要讲了些什么？" },
  { word: "注意", pinyin: "zhùyì", meaning: "to pay attention", example: "请注意安全。" },
  { word: "着急", pinyin: "zháojí", meaning: "to worry", example: "遇到事情，不要着急。" },
  { word: "自己", pinyin: "zìjǐ", meaning: "oneself", example: "我喜欢自己一个人旅游。" },
  { word: "总是", pinyin: "zǒngshì", meaning: "always", example: "他总是很早起床。" },
  { word: "嘴", pinyin: "zuǐ", meaning: "mouth", example: "妹妹的嘴边有一粒米。" },
  { word: "最近", pinyin: "zuìjìn", meaning: "recently", example: "我最近很忙。" },
  { word: "作业", pinyin: "zuòyè", meaning: "homework", example: "今天的作业你写完了吗？" },
  { word: "作用", pinyin: "zuòyòng", meaning: "effect", example: "这种感冒药对我没什么作用。" }
];
